package com.makeeb.platform.clipboard

import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import platform.UIKit.UIPasteboard

/**
 * The general pasteboard. iOS has no change callback a keyboard extension can use, so [changes]
 * polls `changeCount` while collected. Reading requires Full Access; [hasAccess] gates it.
 */
class PasteboardSystemClipboard(
    private val hasAccess: () -> Boolean,
    private val pollIntervalMillis: Long = 1_000,
) : SystemClipboard {
    private val pasteboard get() = UIPasteboard.generalPasteboard

    override fun read(): Clip? {
        if (!hasAccess() || !pasteboard.hasStrings) return null
        val text = pasteboard.string?.takeIf { it.isNotEmpty() } ?: return null
        return Clip(text, isSensitive = pasteboard.pasteboardTypes.any { it in SENSITIVE_TYPES })
    }

    override fun write(text: String) {
        if (hasAccess()) pasteboard.string = text
    }

    private companion object {
        /**
         * Markers password managers (1Password, Bitwarden, KeePassium…) and other apps put next to
         * secrets they copy: http://nspasteboard.org
         */
        val SENSITIVE_TYPES = setOf(
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
        )
    }

    override val changes: Flow<Clip> = flow {
        var lastChangeCount = pasteboard.changeCount
        while (true) {
            delay(pollIntervalMillis)
            val changeCount = pasteboard.changeCount
            if (changeCount != lastChangeCount) {
                lastChangeCount = changeCount
                read()?.let { emit(it) }
            }
        }
    }
}
