// Generated by scripts/import-aosp-layouts.py; do not edit.
// Unicode CLDR 48.2.2 (cldr-json), main exemplar characters.
// Data © Unicode, Inc. SPDX-License-Identifier: Unicode-3.0
package com.makeeb.engine.layout

/** The letters each bundled language needs (CLDR main exemplars), without multi-letter sequences. */
internal val cldrMainExemplars: Map<String, String> = mapOf(
    "en" to "a b c d e f g h i j k l m n o p q r s t u v w x y z",
    "de" to "a ä b c d e f g h i j k l m n o ö p q r s ß t u ü v w x y z",
    "fr" to "a à â æ b c ç d e é è ê ë f g h i î ï j k l m n o ô œ p q r s t u ù û ü v w x y ÿ z",
    "es" to "a á b c d e é f g h i í j k l m n ñ o ó p q r s t u ú ü v w x y z",
    "it" to "a à b c d e é è f g h i ì j k l m n o ò p q r s t u ù v w x y z",
    "pt" to "a á à â ã b c ç d e é ê f g h i í j k l m n o ó ò ô õ p q r s t u ú v w x y z",
    "hu" to "a á b c d e é f g h i í j k l m n o ó ö ő p r s t u ú ü ű v z",
    "pl" to "a ą b c ć d e ę f g h i j k l ł m n ń o ó p r s ś t u w y z ź ż",
    "nl" to "a á ä b c d e é ë f g h i í ï j k l m n o ó ö p q r s t u ú ü v w x y z",
    "sv" to "a à b c d e é f g h i j k l m n o p q r s t u v w x y z å ä ö",
)
