#!/usr/bin/env python3
"""Embed MaKeeb's layout data in Kotlin.

    scripts/generate-layout-data.py

Reads engine/layout/data/bundle.json (which files ship, in the order settings list them) and the
layout and language files it names, and writes
engine/layout/src/commonMain/kotlin/com/makeeb/engine/layout/data/BundledLayoutData.kt with each
file's text in a raw-string constant. Engine modules have no resource loading; the keyboard
parses a file the first time it needs it (BuiltInLayoutProvider). The files are embedded as
written, so the Kotlin validator sees exactly what is in the repository.
"""
import json
import os
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
DATA = os.path.join(ROOT, "engine", "layout", "data")
OUT = os.path.join(ROOT, "engine", "layout", "src", "commonMain", "kotlin", "com", "makeeb", "engine",
                   "layout", "data", "BundledLayoutData.kt")


def read(kind: str, name: str) -> str:
    path = os.path.join(DATA, kind, f"{name}.json")
    with open(path, encoding="utf-8") as f:
        text = f.read()
    if '"""' in text:
        sys.exit(f"{path}: contains a triple quote")
    return text.strip().replace("$", "${'$'}")


def listed(kind: str, names: list):
    on_disk = sorted(f[:-5] for f in os.listdir(os.path.join(DATA, kind)) if f.endswith(".json"))
    missing = [n for n in names if n not in on_disk]
    unlisted = [n for n in on_disk if n not in names]
    if missing or unlisted or len(set(names)) != len(names):
        sys.exit(f"bundle.json {kind}: missing files {missing}, files not listed {unlisted}, or a duplicate")


def main():
    with open(os.path.join(DATA, "bundle.json"), encoding="utf-8") as f:
        bundle = json.load(f)
    for kind in ("layouts", "languages"):
        listed(kind, bundle[kind])
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/generate-layout-data.py from engine/layout/data; do not edit.\n")
        f.write("// Sources and licences: each file's \"sources\" and THIRD_PARTY_NOTICES.md.\n")
        f.write("package com.makeeb.engine.layout.data\n\n")
        sections = []
        for kind, name in (("layouts", "bundledLayoutFiles"), ("languages", "bundledLanguageFiles")):
            what = "Layout files (letter rows), by id" if kind == "layouts" else "Language files, by tag"
            entries = "".join(f'    BundledFile(\n        "{entry}",\n        """{read(kind, entry)}""",\n    ),\n'
                              for entry in bundle[kind])
            sections.append(f"/** {what}, in the order settings list them. */\n"
                            f"internal val {name}: List<BundledFile> = listOf(\n{entries})\n")
        f.write("\n".join(sections))
    total = sum(len(bundle[k]) for k in ("layouts", "languages"))
    print(f"{total} files -> {os.path.relpath(OUT, ROOT)}")


main()
