#!/usr/bin/env python3
"""Generate the emoji catalogue from Unicode and CLDR data.

    scripts/generate-emoji-data.py [--emoji 15.1] [--cldr 44] [--lang en]

Downloads emoji-test.txt (the RGI emoji in CLDR order, with groups) and the CLDR annotations
(names and search keywords, including derived ones for sequences), and writes
engine/emoji/src/commonMain/kotlin/com/makeeb/engine/emoji/data/EmojiData<Lang>.kt: one
tab-separated line per emoji, `emoji <TAB> category <TAB> name <TAB> keyword|keyword…`, in chunked
raw strings (Kotlin constants have a size limit). Skin-tone variants are left out; the base emoji
is flagged when tones exist (`+` after the category). Data © Unicode, Inc., Unicode-DFS-2016.
"""
import argparse
import os
import re
import urllib.request
import xml.etree.ElementTree as ET

GROUPS = {
    "Smileys & Emotion": 0, "People & Body": 0, "Animals & Nature": 1, "Food & Drink": 2,
    "Activities": 3, "Travel & Places": 4, "Objects": 5, "Symbols": 6, "Flags": 7,
}
TONES = set(range(0x1F3FB, 0x1F400))
CHUNK_BYTES = 48_000

ap = argparse.ArgumentParser()
ap.add_argument("--emoji", default="15.1")
ap.add_argument("--cldr", default="44")
ap.add_argument("--lang", default="en")
args = ap.parse_args()


def fetch(url: str) -> str:
    with urllib.request.urlopen(url) as response:
        return response.read().decode("utf-8")


def annotations(xml: str) -> dict:
    found = {}
    for node in ET.fromstring(xml).iter("annotation"):
        cp = node.get("cp").replace("️", "")
        entry = found.setdefault(cp, {"name": None, "keywords": []})
        if node.get("type") == "tts":
            entry["name"] = node.text.strip()
        else:
            entry["keywords"] = [k.strip() for k in node.text.split("|") if k.strip()]
    return found


test = fetch(f"https://unicode.org/Public/emoji/{args.emoji}/emoji-test.txt")
cldr = f"https://raw.githubusercontent.com/unicode-org/cldr/release-{args.cldr}/common"
names = annotations(fetch(f"{cldr}/annotations/{args.lang}.xml"))
names.update(annotations(fetch(f"{cldr}/annotationsDerived/{args.lang}.xml")))

emoji, toned, group = [], set(), None
for line in test.splitlines():
    if line.startswith("# group:"):
        group = line.split(":", 1)[1].strip()
        continue
    match = re.match(r"^([0-9A-F ]+?)\s*; fully-qualified\s*# (\S+) E[\d.]+ (.+)$", line)
    if not match or group not in GROUPS:
        continue
    points = [int(p, 16) for p in match.group(1).split()]
    if TONES & set(points):
        toned.add("".join(chr(p) for p in points if p not in TONES))
        continue
    emoji.append((match.group(2), GROUPS[group], match.group(3)))

lines = []
for value, category, fallback in emoji:
    entry = names.get(value.replace("️", ""), {})
    name = (entry.get("name") or fallback).lower()
    keywords = [k.lower() for k in entry.get("keywords", []) if k.lower() != name]
    tones = "+" if value in toned or value.replace("️", "") in {t.replace("️", "") for t in toned} else ""
    fields = [value, f"{category}{tones}", name, "|".join(dict.fromkeys(keywords))]
    lines.append("\t".join(f.replace("\t", " ") for f in fields))

chunks, current = [], []
for line in lines:
    if sum(len(l.encode()) + 1 for l in current) + len(line.encode()) > CHUNK_BYTES:
        chunks.append(current)
        current = []
    current.append(line)
chunks.append(current)

lang = args.lang.capitalize()
out = os.path.join(os.path.dirname(__file__), "..", "engine", "emoji", "src", "commonMain", "kotlin",
                   "com", "makeeb", "engine", "emoji", "data", f"EmojiData{lang}.kt")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w") as f:
    f.write("// Generated by scripts/generate-emoji-data.py; do not edit.\n")
    f.write(f"// Emoji {args.emoji} (emoji-test.txt) and CLDR {args.cldr} annotations ({args.lang}).\n")
    f.write("// Data © 1991-2023 Unicode, Inc. SPDX-License-Identifier: Unicode-DFS-2016\n")
    f.write("package com.makeeb.engine.emoji.data\n\n")
    f.write(f"/** {len(lines)} emoji: `emoji<TAB>category[+ if it has skin tones]<TAB>name<TAB>keyword|…`. */\n")
    f.write(f"internal val emojiData{lang}: Array<String> = arrayOf(\n")
    for chunk in chunks:
        body = "\n".join(chunk).replace("$", "${'$'}")
        f.write(f'    """{body}""",\n')
    f.write(")\n")
print(f"{len(lines)} emoji, {len(toned)} with skin tones, {len(chunks)} chunks -> {os.path.relpath(out)}")
