package com.makeeb.engine.emoji

import com.makeeb.engine.emoji.data.emojiDataEn

/**
 * Every RGI emoji (Unicode 15.1) with English CLDR names and keywords, generated by
 * `scripts/generate-emoji-data.py`. The data sits in the binary as text and is parsed on first
 * use, so a keyboard that never opens the emoji panel never pays for it.
 */
class BundledEmojiCatalog : EmojiCatalog {
    private val all: List<Emoji> by lazy { parse(emojiDataEn) }
    private val byCategory by lazy { all.groupBy { it.category } }

    override val categories: List<EmojiCategory> = EmojiCategory.entries

    override fun emojis(category: EmojiCategory): List<Emoji> = byCategory[category].orEmpty()

    /**
     * Every word of [query] must start a word of the emoji's name or keywords. Tiers: the name is
     * the query; the name starts with it or a keyword is it; all words match name words; all
     * match name or keyword words. Within a tier the most used emoji come first, then CLDR order.
     */
    override fun search(query: String, limit: Int): List<Emoji> {
        val needle = query.trim().lowercase()
        if (needle.isEmpty()) return emptyList()
        val terms = needle.split(' ').filter { it.isNotEmpty() }
        return all.asSequence()
            .mapNotNull { emoji -> tier(emoji, needle, terms)?.let { emoji to it * TIER + popularity(emoji) } }
            .sortedBy { it.second } // stable: CLDR order breaks ties
            .take(limit)
            .map { it.first }
            .toList()
    }

    private fun tier(emoji: Emoji, needle: String, terms: List<String>): Int? {
        val nameWords = emoji.name.split(' ', '-')
        val keywordWords = emoji.keywords.flatMap { it.split(' ', '-') }
        fun matches(words: List<String>) = terms.all { term -> words.any { it.startsWith(term) } }
        return when {
            emoji.name == needle -> 0
            emoji.name.startsWith(needle) || needle in emoji.keywords -> 1
            matches(nameWords) -> 2
            matches(nameWords + keywordWords) -> 3
            else -> null
        }
    }

    private fun popularity(emoji: Emoji): Int = POPULAR.indexOf(emoji.value).let { if (it < 0) POPULAR.size else it }

    private companion object {
        const val TIER = 1000

        /** The most used emoji, most used first (Unicode emoji frequency data, 2021). */
        val POPULAR = listOf(
            "😂", "❤️", "🤣", "👍", "😭", "🙏", "😘", "🥰", "😍", "😊", "🎉", "😁", "💕", "🥺", "😅", "🔥",
            "☺️", "🤦", "♥️", "🤷", "🙄", "😆", "🤗", "😉", "🎂", "🤔", "👏", "🙂", "😳", "🥳", "😎", "👌",
            "💜", "😔", "💪", "✨", "💖", "👀", "😋", "😏", "😢", "👉", "💗", "😩", "💯", "🌹", "💞", "🎈",
            "💙", "😃", "😡", "💐", "😜", "🙈", "🤞", "😄", "🤤", "🙌", "🤪", "❣️", "😀", "💋", "💀", "👇",
            "💔", "😌", "💓", "🤩", "🙃", "😬", "😱", "😴", "🤭", "😐", "🌞", "😒", "😇", "🌸", "😈", "🎶",
        )

        fun parse(chunks: Array<String>): List<Emoji> = buildList {
            for (chunk in chunks) {
                for (line in chunk.lineSequence()) {
                    val fields = line.split('\t')
                    if (fields.size < 3) continue
                    val category = fields[1]
                    add(
                        Emoji(
                            value = fields[0],
                            name = fields[2],
                            category = EmojiCategory.entries[category[0] - '0'],
                            keywords = fields.getOrNull(3)?.takeIf { it.isNotEmpty() }?.split('|').orEmpty(),
                            hasSkinTones = category.endsWith('+'),
                        ),
                    )
                }
            }
        }
    }
}
