package com.makeeb.engine.emoji

import com.makeeb.engine.emoji.data.emojiDataEn

/**
 * Every RGI emoji (Unicode 15.1) with English CLDR names and keywords, generated by
 * `scripts/generate-emoji-data.py`. The data stays the static text it is compiled into: a single
 * pass records where each line and field starts (a few primitive arrays), [Emoji] objects are
 * created only for the category shown or the search matches, and search compares words in place.
 * Materialising the whole catalogue cost the iOS keyboard extension ~18 MB (APP-111).
 */
class BundledEmojiCatalog : EmojiCatalog {
    private val lines: Lines by lazy { Lines(emojiDataEn) }

    override val categories: List<EmojiCategory> = EmojiCategory.entries

    override fun emojis(category: EmojiCategory): List<Emoji> {
        val all = lines
        return (0 until all.count).filter { all.category[it].toInt() == category.ordinal }.map(all::emoji)
    }

    override fun find(value: String): Emoji? {
        val all = lines
        return (0 until all.count).firstOrNull { all.valueEquals(it, value) }?.let(all::emoji)
    }

    /**
     * Every word of [query] must start a word of the emoji's name or keywords. Tiers: the name is
     * the query; the name starts with it or a keyword is it; all words match name words; all
     * match name or keyword words. Within a tier the most used emoji come first, then CLDR order.
     */
    override fun search(query: String, limit: Int): List<Emoji> {
        val needle = query.trim().lowercase()
        if (needle.isEmpty()) return emptyList()
        val terms = needle.split(' ').filter { it.isNotEmpty() }
        val all = lines
        val ranked = ArrayList<Pair<Int, Int>>() // line, score
        for (line in 0 until all.count) {
            val tier = all.tier(line, needle, terms) ?: continue
            ranked += line to tier * TIER + popularity(all.value(line))
        }
        return ranked.sortedBy { it.second }.take(limit).map { all.emoji(it.first) } // stable: CLDR order breaks ties
    }

    override fun forWord(word: String): Emoji? {
        val needle = word.trim().lowercase()
        if (needle.isEmpty()) return null
        val all = lines
        var best = -1
        var bestScore = Int.MAX_VALUE
        for (line in 0 until all.count) {
            val tier = all.exactTier(line, needle) ?: continue
            val score = tier * TIER + popularity(all.value(line))
            if (score < bestScore) {
                best = line
                bestScore = score
            }
        }
        return if (best < 0) null else all.emoji(best)
    }

    private fun popularity(value: String): Int = POPULAR.indexOf(value).let { if (it < 0) POPULAR.size else it }

    /** Line and field offsets into the data chunks: `emoji<TAB>category[+]<TAB>name<TAB>keyword|…`. */
    private class Lines(private val chunks: Array<String>) {
        val count: Int
        private val chunk: IntArray
        private val start: IntArray
        private val nameStart: IntArray
        private val nameEnd: IntArray
        private val end: IntArray
        val category: ByteArray
        private val tones: BooleanArray

        init {
            var total = 0
            for (c in chunks) total += c.count { it == '\n' } + 1
            chunk = IntArray(total); start = IntArray(total); nameStart = IntArray(total); nameEnd = IntArray(total)
            end = IntArray(total); category = ByteArray(total); tones = BooleanArray(total)
            var n = 0
            chunks.forEachIndexed { c, text ->
                var lineStart = 0
                while (lineStart < text.length) {
                    val lineEnd = text.indexOf('\n', lineStart).let { if (it < 0) text.length else it }
                    val tab1 = text.indexOf('\t', lineStart)
                    val tab2 = text.indexOf('\t', tab1 + 1)
                    if (tab1 in lineStart until lineEnd && tab2 in lineStart until lineEnd) {
                        val tab3 = text.indexOf('\t', tab2 + 1).let { if (it < 0 || it > lineEnd) lineEnd else it }
                        chunk[n] = c; start[n] = lineStart; nameStart[n] = tab2 + 1; nameEnd[n] = tab3; end[n] = lineEnd
                        category[n] = (text[tab1 + 1] - '0').toByte()
                        tones[n] = text[tab2 - 1] == '+'
                        n++
                    }
                    lineStart = lineEnd + 1
                }
            }
            count = n
        }

        private fun text(line: Int) = chunks[chunk[line]]
        private fun valueEnd(line: Int) = text(line).indexOf('\t', start[line])
        private fun keywordsStart(line: Int) = if (nameEnd[line] < end[line]) nameEnd[line] + 1 else end[line]

        fun value(line: Int): String = text(line).substring(start[line], valueEnd(line))

        fun valueEquals(line: Int, value: String): Boolean {
            val from = start[line]
            return valueEnd(line) - from == value.length && text(line).regionMatches(from, value, 0, value.length)
        }

        fun emoji(line: Int): Emoji {
            val text = text(line)
            val keywords = keywordsStart(line).let { if (it < end[line]) text.substring(it, end[line]).split('|') else emptyList() }
            return Emoji(value(line), text.substring(nameStart[line], nameEnd[line]), EmojiCategory.entries[category[line].toInt()], keywords, tones[line])
        }

        fun tier(line: Int, needle: String, terms: List<String>): Int? {
            val text = text(line)
            val ns = nameStart[line]
            val ne = nameEnd[line]
            val ks = keywordsStart(line)
            val ke = end[line]
            return when {
                ne - ns == needle.length && text.regionMatches(ns, needle, 0, needle.length) -> 0
                (ne - ns >= needle.length && text.regionMatches(ns, needle, 0, needle.length)) || hasKeyword(text, ks, ke, needle) -> 1
                terms.all { anyWordStarts(text, ns, ne, it) } -> 2
                terms.all { anyWordStarts(text, ns, ne, it) || anyWordStarts(text, ks, ke, it) } -> 3
                else -> null
            }
        }

        /** 0 when the name is [word], 1 when a keyword is, else null. */
        fun exactTier(line: Int, word: String): Int? {
            val text = text(line)
            val ns = nameStart[line]
            return when {
                nameEnd[line] - ns == word.length && text.regionMatches(ns, word, 0, word.length) -> 0
                hasKeyword(text, keywordsStart(line), end[line], word) -> 1
                else -> null
            }
        }

        private fun hasKeyword(text: String, from: Int, to: Int, keyword: String): Boolean {
            var i = from
            while (i < to) {
                val next = text.indexOf('|', i).let { if (it < 0 || it > to) to else it }
                if (next - i == keyword.length && text.regionMatches(i, keyword, 0, keyword.length)) return true
                i = next + 1
            }
            return false
        }

        private fun anyWordStarts(text: String, from: Int, to: Int, term: String): Boolean {
            for (i in from..to - term.length) {
                if ((i == from || text[i - 1] == ' ' || text[i - 1] == '-' || text[i - 1] == '|') && text.regionMatches(i, term, 0, term.length)) return true
            }
            return false
        }
    }

    private companion object {
        const val TIER = 1000

        /** The most used emoji, most used first (Unicode emoji frequency data, 2021). */
        val POPULAR = listOf(
            "😂", "❤️", "🤣", "👍", "😭", "🙏", "😘", "🥰", "😍", "😊", "🎉", "😁", "💕", "🥺", "😅", "🔥",
            "☺️", "🤦", "♥️", "🤷", "🙄", "😆", "🤗", "😉", "🎂", "🤔", "👏", "🙂", "😳", "🥳", "😎", "👌",
            "💜", "😔", "💪", "✨", "💖", "👀", "😋", "😏", "😢", "👉", "💗", "😩", "💯", "🌹", "💞", "🎈",
            "💙", "😃", "😡", "💐", "😜", "🙈", "🤞", "😄", "🤤", "🙌", "🤪", "❣️", "😀", "💋", "💀", "👇",
            "💔", "😌", "💓", "🤩", "🙃", "😬", "😱", "😴", "🤭", "😐", "🌞", "😒", "😇", "🌸", "😈", "🎶",
        )
    }
}
