// Generated by scripts/generate-layout-data.py from engine/layout/data; do not edit.
// Sources and licences: each file's "sources" and THIRD_PARTY_NOTICES.md.
package com.makeeb.engine.layout.data

/** Layout files (letter rows), by id, in the order settings list them. */
internal val bundledLayoutFiles: List<BundledFile> = listOf(
    BundledFile(
        "qwerty",
        """{
  "schema": 1,
  "id": "qwerty",
  "name": "QWERTY",
  "rows": [
    "q w e r t y u i o p",
    "a s d f g h j k l",
    "z x c v b n m"
  ],
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/xml/rows_qwerty.xml"
  ]
}""",
    ),
    BundledFile(
        "qwertz",
        """{
  "schema": 1,
  "id": "qwertz",
  "name": "QWERTZ",
  "rows": [
    "q w e r t z u i o p",
    "a s d f g h j k l",
    "y x c v b n m"
  ],
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/xml/rows_qwertz.xml"
  ]
}""",
    ),
    BundledFile(
        "azerty",
        """{
  "schema": 1,
  "id": "azerty",
  "name": "AZERTY",
  "rows": [
    "a z e r t y u i o p",
    "q s d f g h j k l m",
    "w x c v b n '"
  ],
  "keys": {
    "'": {
      "alternates": "’ \""
    }
  },
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/xml/rows_azerty.xml",
    "MaKeeb: scripts/import-aosp-layouts.py MAKEEB_RULES"
  ]
}""",
    ),
    BundledFile(
        "dvorak",
        """{
  "schema": 1,
  "id": "dvorak",
  "name": "Dvorak",
  "rows": [
    "' , . p y f g c r l",
    "a o e u i d h t n s",
    "q j k x b m w v z"
  ],
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/xml/rows_dvorak.xml",
    "MaKeeb: scripts/import-aosp-layouts.py MAKEEB_RULES"
  ]
}""",
    ),
    BundledFile(
        "colemak",
        """{
  "schema": 1,
  "id": "colemak",
  "name": "Colemak",
  "rows": [
    "q w f p g j l u y",
    "a r s t d h n e i o",
    "z x c v b k m"
  ],
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/xml/rows_colemak.xml",
    "MaKeeb: scripts/import-aosp-layouts.py MAKEEB_RULES"
  ]
}""",
    ),
    BundledFile(
        "workman",
        """{
  "schema": 1,
  "id": "workman",
  "name": "Workman",
  "rows": [
    "q d r w b j f u p",
    "a s h t g y n e o i",
    "z x m c v k l"
  ],
  "sources": [
    "MaKeeb: hand-written; AOSP LatinIME has no Workman layout"
  ]
}""",
    ),
)

/** Language files, by tag, in the order settings list them. */
internal val bundledLanguageFiles: List<BundledFile> = listOf(
    BundledFile(
        "en",
        """{
  "schema": 1,
  "language": "en",
  "name": "English",
  "autonym": "English",
  "layouts": [
    "qwerty"
  ],
  "alternates": {
    "a": "à á â ä æ ã å ā",
    "c": "ç",
    "e": "é è ê ë ē",
    "i": "í î ï ī ì",
    "n": "ñ",
    "o": "ó ô ö ò œ ø ō õ",
    "s": "ß",
    "u": "ú û ü ù ū"
  },
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): tools/make-keyboard-text/res/values-en/donottranslate-more-keys.xml",
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/values/donottranslate.xml, java/res/xml/method.xml (layouts)"
  ]
}""",
    ),
    BundledFile(
        "de",
        """{
  "schema": 1,
  "language": "de",
  "name": "German",
  "autonym": "Deutsch",
  "layouts": [
    "qwertz"
  ],
  "alternates": {
    "a": "ä â à á æ ã å ā",
    "e": "é è ê ë ė",
    "n": "ñ ń",
    "o": "ö ô ò ó õ œ ø ō",
    "s": "ß ś š",
    "u": "ü û ù ú ū"
  },
  "shifted": {
    "ß": "ẞ"
  },
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): tools/make-keyboard-text/res/values-de/donottranslate-more-keys.xml",
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/values/donottranslate.xml, java/res/xml/method.xml (layouts)",
    "MaKeeb: shifted forms"
  ]
}""",
    ),
    BundledFile(
        "fr",
        """{
  "schema": 1,
  "language": "fr",
  "name": "French",
  "autonym": "Français",
  "layouts": [
    "azerty",
    "qwerty",
    "qwertz"
  ],
  "alternates": {
    "a": "à â æ á ä ã å ā ª",
    "c": "ç ć č",
    "e": "é è ê ë ę ė ē",
    "i": "î ï ì í į ī",
    "o": "ô œ ö ò ó õ ø ō º",
    "u": "ù û ü ú ū",
    "y": "ÿ"
  },
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): tools/make-keyboard-text/res/values-fr/donottranslate-more-keys.xml",
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/values/donottranslate.xml, java/res/xml/method.xml (layouts)"
  ]
}""",
    ),
    BundledFile(
        "es",
        """{
  "schema": 1,
  "language": "es",
  "name": "Spanish",
  "autonym": "Español",
  "layouts": [
    "qwerty"
  ],
  "alternates": {
    "a": "á à ä â ã å ą æ ā ª",
    "c": "ç ć č",
    "e": "é è ë ê ę ė ē",
    "i": "í ï ì î į ī",
    "n": "ñ ń",
    "o": "ó ò ö ô õ ø œ ō º",
    "u": "ú ü ù û ū"
  },
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): tools/make-keyboard-text/res/values-es/donottranslate-more-keys.xml",
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/values/donottranslate.xml, java/res/xml/method.xml (layouts)"
  ]
}""",
    ),
    BundledFile(
        "it",
        """{
  "schema": 1,
  "language": "it",
  "name": "Italian",
  "autonym": "Italiano",
  "layouts": [
    "qwerty",
    "qwertz"
  ],
  "alternates": {
    "a": "à á â ä æ ã å ā ª",
    "e": "è é ê ë ę ė ē",
    "i": "ì í î ï į ī",
    "o": "ò ó ô ö õ œ ø ō º",
    "u": "ù ú û ü ū"
  },
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): tools/make-keyboard-text/res/values-it/donottranslate-more-keys.xml",
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/values/donottranslate.xml, java/res/xml/method.xml (layouts)"
  ]
}""",
    ),
    BundledFile(
        "pt",
        """{
  "schema": 1,
  "language": "pt",
  "name": "Portuguese",
  "autonym": "Português",
  "layouts": [
    "qwerty"
  ],
  "alternates": {
    "a": "á ã à â ä å æ ª",
    "c": "ç č ć",
    "e": "é ê è ę ė ē ë",
    "i": "í î ì ï į ī",
    "o": "ó õ ô ò ö œ ø ō º",
    "u": "ú ü ù û ū"
  },
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): tools/make-keyboard-text/res/values-pt/donottranslate-more-keys.xml",
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/values/donottranslate.xml, java/res/xml/method.xml (layouts)"
  ]
}""",
    ),
    BundledFile(
        "hu",
        """{
  "schema": 1,
  "language": "hu",
  "name": "Hungarian",
  "autonym": "Magyar",
  "layouts": [
    "qwertz"
  ],
  "alternates": {
    "a": "á à â ä æ ã å ā",
    "e": "é è ê ë ę ė ē",
    "i": "í î ï ì į ī",
    "o": "ó ö ő ô ò õ œ ø ō",
    "u": "ú ü ű û ù ū"
  },
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): tools/make-keyboard-text/res/values-hu/donottranslate-more-keys.xml",
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/values/donottranslate.xml, java/res/xml/method.xml (layouts)"
  ]
}""",
    ),
    BundledFile(
        "pl",
        """{
  "schema": 1,
  "language": "pl",
  "name": "Polish",
  "autonym": "Polski",
  "layouts": [
    "qwerty"
  ],
  "alternates": {
    "a": "ą á à â ä æ ã å ā",
    "c": "ć ç č",
    "e": "ę è é ê ë ė ē",
    "l": "ł",
    "n": "ń ñ",
    "o": "ó ö ô ò õ œ ø ō",
    "s": "ś ß š",
    "z": "ż ź ž"
  },
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): tools/make-keyboard-text/res/values-pl/donottranslate-more-keys.xml",
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/values/donottranslate.xml, java/res/xml/method.xml (layouts)"
  ]
}""",
    ),
    BundledFile(
        "nl",
        """{
  "schema": 1,
  "language": "nl",
  "name": "Dutch",
  "autonym": "Nederlands",
  "layouts": [
    "qwerty",
    "azerty"
  ],
  "alternates": {
    "a": "á ä â à æ ã å ā",
    "e": "é ë ê è ę ė ē",
    "i": "í ï ì î į ī ĳ",
    "n": "ñ ń",
    "o": "ó ö ô ò õ œ ø ō",
    "u": "ú ü û ù ū",
    "y": "ĳ"
  },
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): tools/make-keyboard-text/res/values-nl/donottranslate-more-keys.xml",
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/values/donottranslate.xml, java/res/xml/method.xml (layouts)"
  ]
}""",
    ),
    BundledFile(
        "sv",
        """{
  "schema": 1,
  "language": "sv",
  "name": "Swedish",
  "autonym": "Svenska",
  "layouts": [
    "qwerty"
  ],
  "alternates": {
    "a": "ä å æ á à â ą ã",
    "c": "ç ć č",
    "d": "ð ď",
    "e": "é è ê ë ę",
    "i": "í ì î ï",
    "l": "ł",
    "n": "ń ñ ň",
    "o": "ö ø œ ó ò ô õ ō",
    "r": "ř",
    "s": "ś š ş ß",
    "t": "ť þ",
    "u": "ü ú ù û ū",
    "y": "ý ÿ",
    "z": "ź ž ż"
  },
  "sources": [
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): tools/make-keyboard-text/res/values-sv/donottranslate-more-keys.xml",
    "AOSP LatinIME 8b211dd233e9 (Apache-2.0): java/res/values/donottranslate.xml, java/res/xml/method.xml (layouts)"
  ]
}""",
    ),
)
