// Generated by scripts/generate-emoji-data.py; do not edit.
// Emoji 15.1 (emoji-test.txt) and CLDR 44 annotations (en).
// Data © 1991-2023 Unicode, Inc. SPDX-License-Identifier: Unicode-DFS-2016
package com.makeeb.engine.emoji.data

/** 1898 emoji: `emoji<TAB>category[+ if it has skin tones]<TAB>name<TAB>keyword|…`. */
internal val emojiDataEn: Array<String> = arrayOf(
    """😀	0	grinning face	face|grin
😃	0	grinning face with big eyes	face|mouth|open|smile
😄	0	grinning face with smiling eyes	eye|face|mouth|open|smile
😁	0	beaming face with smiling eyes	eye|face|grin|smile
😆	0	grinning squinting face	face|laugh|mouth|satisfied|smile
😅	0	grinning face with sweat	cold|face|open|smile|sweat
🤣	0	rolling on the floor laughing	face|floor|laugh|rofl|rolling|rotfl
😂	0	face with tears of joy	face|joy|laugh|tear
🙂	0	slightly smiling face	face|smile
🙃	0	upside-down face	face|upside-down
🫠	0	melting face	disappear|dissolve|liquid|melt
😉	0	winking face	face|wink
😊	0	smiling face with smiling eyes	blush|eye|face|smile
😇	0	smiling face with halo	angel|face|fantasy|halo|innocent
🥰	0	smiling face with hearts	adore|crush|hearts|in love
😍	0	smiling face with heart-eyes	eye|face|love|smile
🤩	0	star-struck	eyes|face|grinning|star
😘	0	face blowing a kiss	face|kiss
😗	0	kissing face	face|kiss
☺️	0	smiling face	face|outlined|relaxed|smile
😚	0	kissing face with closed eyes	closed|eye|face|kiss
😙	0	kissing face with smiling eyes	eye|face|kiss|smile
🥲	0	smiling face with tear	grateful|proud|relieved|smiling|tear|touched
😋	0	face savoring food	delicious|face|savouring|smile|yum
😛	0	face with tongue	face|tongue
😜	0	winking face with tongue	eye|face|joke|tongue|wink
🤪	0	zany face	eye|goofy|large|small
😝	0	squinting face with tongue	eye|face|horrible|taste|tongue
🤑	0	money-mouth face	face|money|mouth
🤗	0	smiling face with open hands	face|hug|hugging|open hands|smiling face
🤭	0	face with hand over mouth	whoops
🫢	0	face with open eyes and hand over mouth	amazement|awe|disbelief|embarrass|scared|surprise
🫣	0	face with peeking eye	captivated|peep|stare
🤫	0	shushing face	quiet|shush
🤔	0	thinking face	face|thinking
🫡	0	saluting face	ok|salute|sunny|troops|yes
🤐	0	zipper-mouth face	face|mouth|zip|zipper
🤨	0	face with raised eyebrow	distrust|skeptic
😐	0	neutral face	deadpan|face|meh|neutral
😑	0	expressionless face	expressionless|face|inexpressive|meh|unexpressive
😶	0	face without mouth	face|mouth|quiet|silent
🫥	0	dotted line face	depressed|disappear|hide|introvert|invisible
😶‍🌫️	0	face in clouds	absentminded|face in the fog|head in clouds
😏	0	smirking face	face|smirk
😒	0	unamused face	face|unamused|unhappy
🙄	0	face with rolling eyes	eyeroll|eyes|face|rolling
😬	0	grimacing face	face|grimace
😮‍💨	0	face exhaling	exhale|gasp|groan|relief|whisper|whistle
🤥	0	lying face	face|lie|pinocchio
🫨	0	shaking face	earthquake|face|shaking|shock|vibrate
🙂‍↔️	0	head shaking horizontally	no|shake
🙂‍↕️	0	head shaking vertically	nod|yes
😌	0	relieved face	face|relieved
😔	0	pensive face	dejected|face|pensive
😪	0	sleepy face	face|good night|sleep
🤤	0	drooling face	drooling|face
😴	0	sleeping face	face|good night|sleep|zzz
😷	0	face with medical mask	cold|doctor|face|mask|sick
🤒	0	face with thermometer	face|ill|sick|thermometer
🤕	0	face with head-bandage	bandage|face|hurt|injury
🤢	0	nauseated face	face|nauseated|vomit
🤮	0	face vomiting	puke|sick|vomit
🤧	0	sneezing face	face|gesundheit|sneeze
🥵	0	hot face	feverish|heat stroke|hot|red-faced|sweating
🥶	0	cold face	blue-faced|cold|freezing|frostbite|icicles
🥴	0	woozy face	dizzy|intoxicated|tipsy|uneven eyes|wavy mouth
😵	0	face with crossed-out eyes	crossed-out eyes|dead|face|knocked out
😵‍💫	0	face with spiral eyes	dizzy|hypnotized|spiral|trouble|whoa
🤯	0	exploding head	mind blown|shocked
🤠	0	cowboy hat face	cowboy|cowgirl|face|hat
🥳	0	partying face	celebration|hat|horn|party
🥸	0	disguised face	disguise|face|glasses|incognito|nose
😎	0	smiling face with sunglasses	bright|cool|face|sun|sunglasses
🤓	0	nerd face	face|geek|nerd
🧐	0	face with monocle	face|monocle|stuffy
😕	0	confused face	confused|face|meh
🫤	0	face with diagonal mouth	disappointed|meh|skeptical|unsure
😟	0	worried face	face|worried
🙁	0	slightly frowning face	face|frown
☹️	0	frowning face	face|frown
😮	0	face with open mouth	face|mouth|open|sympathy
😯	0	hushed face	face|hushed|stunned|surprised
😲	0	astonished face	astonished|face|shocked|totally
😳	0	flushed face	dazed|face|flushed
🥺	0	pleading face	begging|mercy|puppy eyes
🥹	0	face holding back tears	angry|cry|proud|resist|sad
😦	0	frowning face with open mouth	face|frown|mouth|open
😧	0	anguished face	anguished|face
😨	0	fearful face	face|fear|fearful|scared
😰	0	anxious face with sweat	blue|cold|face|rushed|sweat
😥	0	sad but relieved face	disappointed|face|relieved|whew
😢	0	crying face	cry|face|sad|tear
😭	0	loudly crying face	cry|face|sad|sob|tear
😱	0	face screaming in fear	face|fear|munch|scared|scream
😖	0	confounded face	confounded|face
😣	0	persevering face	face|persevere
😞	0	disappointed face	disappointed|face
😓	0	downcast face with sweat	cold|face|sweat
😩	0	weary face	face|tired|weary
😫	0	tired face	face|tired
🥱	0	yawning face	bored|tired|yawn
😤	0	face with steam from nose	face|triumph|won
😡	0	enraged face	angry|enraged|face|mad|pouting|rage|red
😠	0	angry face	anger|angry|face|mad
🤬	0	face with symbols on mouth	swearing
😈	0	smiling face with horns	face|fairy tale|fantasy|horns|smile
👿	0	angry face with horns	demon|devil|face|fantasy|imp
💀	0	skull	death|face|fairy tale|monster
☠️	0	skull and crossbones	crossbones|death|face|monster|skull
💩	0	pile of poo	dung|face|monster|poo|poop
🤡	0	clown face	clown|face
👹	0	ogre	creature|face|fairy tale|fantasy|monster
👺	0	goblin	creature|face|fairy tale|fantasy|monster
👻	0	ghost	creature|face|fairy tale|fantasy|monster
👽	0	alien	creature|extraterrestrial|face|fantasy|ufo
👾	0	alien monster	alien|creature|extraterrestrial|face|monster|ufo
🤖	0	robot	face|monster
😺	0	grinning cat	cat|face|grinning|mouth|open|smile
😸	0	grinning cat with smiling eyes	cat|eye|face|grin|smile
😹	0	cat with tears of joy	cat|face|joy|tear
😻	0	smiling cat with heart-eyes	cat|eye|face|heart|love|smile
😼	0	cat with wry smile	cat|face|ironic|smile|wry
😽	0	kissing cat	cat|eye|face|kiss
🙀	0	weary cat	cat|face|oh|surprised|weary
😿	0	crying cat	cat|cry|face|sad|tear
😾	0	pouting cat	cat|face|pouting
🙈	0	see-no-evil monkey	evil|face|forbidden|monkey|see
🙉	0	hear-no-evil monkey	evil|face|forbidden|hear|monkey
🙊	0	speak-no-evil monkey	evil|face|forbidden|monkey|speak
💌	0	love letter	heart|letter|love|mail
💘	0	heart with arrow	arrow|cupid
💝	0	heart with ribbon	ribbon|valentine
💖	0	sparkling heart	excited|sparkle
💗	0	growing heart	excited|growing|nervous|pulse
💓	0	beating heart	beating|heartbeat|pulsating
💞	0	revolving hearts	revolving
💕	0	two hearts	love
💟	0	heart decoration	heart
❣️	0	heart exclamation	exclamation|mark|punctuation
💔	0	broken heart	break|broken
❤️‍🔥	0	heart on fire	burn|heart|love|lust|sacred heart
❤️‍🩹	0	mending heart	healthier|improving|mending|recovering|recuperating|well
❤️	0	red heart	heart
🩷	0	pink heart	cute|heart|like|love|pink
🧡	0	orange heart	orange
💛	0	yellow heart	yellow
💚	0	green heart	green
💙	0	blue heart	blue
🩵	0	light blue heart	cyan|heart|light blue|teal
💜	0	purple heart	purple
🤎	0	brown heart	brown|heart
🖤	0	black heart	black|evil|wicked
🩶	0	grey heart	gray|heart|silver|slate
🤍	0	white heart	heart|white
💋	0	kiss mark	kiss|lips
💯	0	hundred points	100|full|hundred|score
💢	0	anger symbol	angry|comic|mad
💥	0	collision	boom|comic
💫	0	dizzy	comic|star
💦	0	sweat droplets	comic|splashing|sweat
💨	0	dashing away	comic|dash|running
🕳️	0	hole	
💬	0	speech balloon	balloon|bubble|comic|dialog|speech
👁️‍🗨️	0	eye in speech bubble	balloon|bubble|eye|speech|witness
🗨️	0	left speech bubble	balloon|bubble|dialog|speech
🗯️	0	right anger bubble	angry|balloon|bubble|mad
💭	0	thought balloon	balloon|bubble|comic|thought
💤	0	zzz	comic|good night|sleep
👋	0+	waving hand	hand|wave|waving
🤚	0+	raised back of hand	backhand|raised
🖐️	0+	hand with fingers splayed	finger|hand|splayed
✋	0+	raised hand	hand|high 5|high five
🖖	0+	vulcan salute	finger|hand|spock|vulcan
🫱	0+	rightwards hand	hand|right|rightward
🫲	0+	leftwards hand	hand|left|leftward
🫳	0+	palm down hand	dismiss|drop|shoo
🫴	0+	palm up hand	beckon|catch|come|offer
🫷	0+	leftwards pushing hand	high five|leftward|push|refuse|stop|wait
🫸	0+	rightwards pushing hand	high five|push|refuse|rightward|stop|wait
👌	0+	ok hand	hand|ok
🤌	0+	pinched fingers	fingers|hand gesture|interrogation|pinched|sarcastic
🤏	0+	pinching hand	small amount
✌️	0+	victory hand	hand|v|victory
🤞	0+	crossed fingers	cross|finger|hand|luck
🫰	0+	hand with index finger and thumb crossed	expensive|heart|love|money|snap
🤟	0+	love-you gesture	hand|ily
🤘	0+	sign of the horns	finger|hand|horns|rock-on
🤙	0+	call me hand	call|hand|hang loose|shaka
👈	0+	backhand index pointing left	backhand|finger|hand|index|point
👉	0+	backhand index pointing right	backhand|finger|hand|index|point
👆	0+	backhand index pointing up	backhand|finger|hand|point|up
🖕	0+	middle finger	finger|hand
👇	0+	backhand index pointing down	backhand|down|finger|hand|point
☝️	0+	index pointing up	finger|hand|index|point|up
🫵	0+	index pointing at the viewer	point|you
👍	0+	thumbs up	+1|hand|thumb|up
👎	0+	thumbs down	-1|down|hand|thumb
✊	0+	raised fist	clenched|fist|hand|punch
👊	0+	oncoming fist	clenched|fist|hand|punch
🤛	0+	left-facing fist	fist|leftwards
🤜	0+	right-facing fist	fist|rightwards
👏	0+	clapping hands	clap|hand
🙌	0+	raising hands	celebration|gesture|hand|hooray|raised
🫶	0+	heart hands	love
👐	0+	open hands	hand|open
🤲	0+	palms up together	prayer
🤝	0+	handshake	agreement|hand|meeting|shake
🙏	0+	folded hands	ask|hand|high 5|high five|please|pray|thanks
✍️	0+	writing hand	hand|write
💅	0+	nail polish	care|cosmetics|manicure|nail|polish
🤳	0+	selfie	camera|phone
💪	0+	flexed biceps	biceps|comic|flex|muscle
🦾	0	mechanical arm	accessibility|prosthetic
🦿	0	mechanical leg	accessibility|prosthetic
🦵	0+	leg	kick|limb
🦶	0+	foot	kick|stomp
👂	0+	ear	body
🦻	0+	ear with hearing aid	accessibility|hard of hearing
👃	0+	nose	body
🧠	0	brain	intelligent
🫀	0	anatomical heart	anatomical|cardiology|heart|organ|pulse
🫁	0	lungs	breath|exhalation|inhalation|organ|respiration
🦷	0	tooth	dentist
🦴	0	bone	skeleton
👀	0	eyes	eye|face
👁️	0	eye	body
👅	0	tongue	body
👄	0	mouth	lips
🫦	0	biting lip	anxious|fear|flirting|nervous|uncomfortable|worried
👶	0+	baby	young
🧒	0+	child	gender-neutral|unspecified gender|young
👦	0+	boy	young
👧	0+	girl	virgo|young|zodiac
🧑	0+	person	adult|gender-neutral|unspecified gender
👱	0+	person: blond hair	blond|blond-haired person|hair
👨	0+	man	adult
🧔	0+	person: beard	beard|person
🧔‍♂️	0+	man: beard	beard|man
🧔‍♀️	0+	woman: beard	beard|woman
👨‍🦰	0+	man: red hair	adult|man|red hair
👨‍🦱	0+	man: curly hair	adult|curly hair|man
👨‍🦳	0+	man: white hair	adult|man|white hair
👨‍🦲	0+	man: bald	adult|bald|man
👩	0+	woman	adult
👩‍🦰	0+	woman: red hair	adult|red hair|woman
🧑‍🦰	0+	person: red hair	adult|gender-neutral|person|red hair|unspecified gender
👩‍🦱	0+	woman: curly hair	adult|curly hair|woman
🧑‍🦱	0+	person: curly hair	adult|curly hair|gender-neutral|person|unspecified gender
👩‍🦳	0+	woman: white hair	adult|white hair|woman
🧑‍🦳	0+	person: white hair	adult|gender-neutral|person|unspecified gender|white hair
👩‍🦲	0+	woman: bald	adult|bald|woman
🧑‍🦲	0+	person: bald	adult|bald|gender-neutral|person|unspecified gender
👱‍♀️	0+	woman: blond hair	blond-haired woman|blonde|hair|woman
👱‍♂️	0+	man: blond hair	blond|blond-haired man|hair|man
🧓	0+	older person	adult|gender-neutral|old|unspecified gender
👴	0+	old man	adult|man|old
👵	0+	old woman	adult|old|woman
🙍	0+	person frowning	frown|gesture
🙍‍♂️	0+	man frowning	frowning|gesture|man
🙍‍♀️	0+	woman frowning	frowning|gesture|woman
🙎	0+	person pouting	gesture|pouting
🙎‍♂️	0+	man pouting	gesture|man|pouting
🙎‍♀️	0+	woman pouting	gesture|pouting|woman
🙅	0+	person gesturing no	forbidden|gesture|hand|prohibited
🙅‍♂️	0+	man gesturing no	forbidden|gesture|hand|man|prohibited
🙅‍♀️	0+	woman gesturing no	forbidden|gesture|hand|prohibited|woman
🙆	0+	person gesturing ok	gesture|hand|ok
🙆‍♂️	0+	man gesturing ok	gesture|hand|man|ok
🙆‍♀️	0+	woman gesturing ok	gesture|hand|ok|woman
💁	0+	person tipping hand	hand|help|information|sassy|tipping
💁‍♂️	0+	man tipping hand	man|sassy|tipping hand
💁‍♀️	0+	woman tipping hand	sassy|tipping hand|woman
🙋	0+	person raising hand	gesture|hand|happy|raised
🙋‍♂️	0+	man raising hand	gesture|man|raising hand
🙋‍♀️	0+	woman raising hand	gesture|raising hand|woman
🧏	0+	deaf person	accessibility|deaf|ear|hear
🧏‍♂️	0+	deaf man	deaf|man
🧏‍♀️	0+	deaf woman	deaf|woman
🙇	0+	person bowing	apology|bow|gesture|sorry
🙇‍♂️	0+	man bowing	apology|bowing|favor|gesture|man|sorry
🙇‍♀️	0+	woman bowing	apology|bowing|favor|gesture|sorry|woman
🤦	0+	person facepalming	disbelief|exasperation|face|palm
🤦‍♂️	0+	man facepalming	disbelief|exasperation|facepalm|man
🤦‍♀️	0+	woman facepalming	disbelief|exasperation|facepalm|woman
🤷	0+	person shrugging	doubt|ignorance|indifference|shrug
🤷‍♂️	0+	man shrugging	doubt|ignorance|indifference|man|shrug
🤷‍♀️	0+	woman shrugging	doubt|ignorance|indifference|shrug|woman
🧑‍⚕️	0+	health worker	doctor|healthcare|nurse|therapist
👨‍⚕️	0+	man health worker	doctor|healthcare|man|nurse|therapist
👩‍⚕️	0+	woman health worker	doctor|healthcare|nurse|therapist|woman
🧑‍🎓	0+	student	graduate
👨‍🎓	0+	man student	graduate|man|student
👩‍🎓	0+	woman student	graduate|student|woman
🧑‍🏫	0+	teacher	instructor|lecturer|professor
👨‍🏫	0+	man teacher	instructor|lecturer|man|professor|teacher
👩‍🏫	0+	woman teacher	instructor|lecturer|professor|teacher|woman
🧑‍⚖️	0+	judge	justice|law|scales
👨‍⚖️	0+	man judge	judge|justice|law|man|scales
👩‍⚖️	0+	woman judge	judge|justice|law|scales|woman
🧑‍🌾	0+	farmer	gardener|rancher
👨‍🌾	0+	man farmer	farmer|gardener|man|rancher
👩‍🌾	0+	woman farmer	farmer|gardener|rancher|woman
🧑‍🍳	0+	cook	chef
👨‍🍳	0+	man cook	chef|cook|man
👩‍🍳	0+	woman cook	chef|cook|woman
🧑‍🔧	0+	mechanic	electrician|plumber|tradesperson
👨‍🔧	0+	man mechanic	electrician|man|mechanic|plumber|tradesperson
👩‍🔧	0+	woman mechanic	electrician|mechanic|plumber|tradesperson|woman
🧑‍🏭	0+	factory worker	assembly|factory|industrial|worker
👨‍🏭	0+	man factory worker	assembly|factory|industrial|man|worker
👩‍🏭	0+	woman factory worker	assembly|factory|industrial|woman|worker
🧑‍💼	0+	office worker	architect|business|manager|white-collar
👨‍💼	0+	man office worker	architect|business|man|manager|white-collar
👩‍💼	0+	woman office worker	architect|business|manager|white-collar|woman
🧑‍🔬	0+	scientist	biologist|chemist|engineer|physicist
👨‍🔬	0+	man scientist	biologist|chemist|engineer|man|physicist|scientist
👩‍🔬	0+	woman scientist	biologist|chemist|engineer|physicist|scientist|woman
🧑‍💻	0+	technologist	coder|developer|inventor|software
👨‍💻	0+	man technologist	coder|developer|inventor|man|software|technologist
👩‍💻	0+	woman technologist	coder|developer|inventor|software|technologist|woman
🧑‍🎤	0+	singer	actor|entertainer|rock|star
👨‍🎤	0+	man singer	actor|entertainer|man|rock|singer|star
👩‍🎤	0+	woman singer	actor|entertainer|rock|singer|star|woman
🧑‍🎨	0+	artist	palette
👨‍🎨	0+	man artist	artist|man|palette
👩‍🎨	0+	woman artist	artist|palette|woman
🧑‍✈️	0+	pilot	plane
👨‍✈️	0+	man pilot	man|pilot|plane
👩‍✈️	0+	woman pilot	pilot|plane|woman
🧑‍🚀	0+	astronaut	rocket
👨‍🚀	0+	man astronaut	astronaut|man|rocket
👩‍🚀	0+	woman astronaut	astronaut|rocket|woman
🧑‍🚒	0+	firefighter	fire|firetruck
👨‍🚒	0+	man firefighter	firefighter|firetruck|man
👩‍🚒	0+	woman firefighter	firefighter|firetruck|woman
👮	0+	police officer	cop|officer|police
👮‍♂️	0+	man police officer	cop|man|officer|police
👮‍♀️	0+	woman police officer	cop|officer|police|woman
🕵️	0+	detective	sleuth|spy
🕵️‍♂️	0+	man detective	detective|man|sleuth|spy
🕵️‍♀️	0+	woman detective	detective|sleuth|spy|woman
💂	0+	guard	
💂‍♂️	0+	man guard	guard|man
💂‍♀️	0+	woman guard	guard|woman
🥷	0+	ninja	fighter|hidden|stealth
👷	0+	construction worker	construction|hat|worker
👷‍♂️	0+	man construction worker	construction|man|worker
👷‍♀️	0+	woman construction worker	construction|woman|worker
🫅	0+	person with crown	monarch|noble|regal|royalty
🤴	0+	prince	
👸	0+	princess	fairy tale|fantasy
👳	0+	person wearing turban	turban
👳‍♂️	0+	man wearing turban	man|turban
👳‍♀️	0+	woman wearing turban	turban|woman
👲	0+	person with skullcap	cap|gua pi mao|hat|person|skullcap
🧕	0+	woman with headscarf	headscarf|hijab|mantilla|tichel
🤵	0+	person in tuxedo	groom|person|tuxedo
🤵‍♂️	0+	man in tuxedo	man|tuxedo
🤵‍♀️	0+	woman in tuxedo	tuxedo|woman
👰	0+	person with veil	bride|person|veil|wedding
👰‍♂️	0+	man with veil	man|veil
👰‍♀️	0+	woman with veil	veil|woman
🤰	0+	pregnant woman	pregnant|woman
🫃	0+	pregnant man	belly|bloated|full|pregnant
🫄	0+	pregnant person	belly|bloated|full|pregnant
🤱	0+	breast-feeding	baby|breast|nursing
👩‍🍼	0+	woman feeding baby	baby|feeding|nursing|woman
👨‍🍼	0+	man feeding baby	baby|feeding|man|nursing
🧑‍🍼	0+	person feeding baby	baby|feeding|nursing|person
👼	0+	baby angel	angel|baby|face|fairy tale|fantasy
🎅	0+	santa claus	celebration|christmas|claus|father|santa
🤶	0+	mrs. claus	celebration|christmas|claus|mother|mrs.
🧑‍🎄	0+	mx claus	christmas|claus
🦸	0+	superhero	good|hero|heroine|superpower
🦸‍♂️	0+	man superhero	good|hero|man|superpower
🦸‍♀️	0+	woman superhero	good|hero|heroine|superpower|woman
🦹	0+	supervillain	criminal|evil|superpower|villain
🦹‍♂️	0+	man supervillain	criminal|evil|man|superpower|villain
🦹‍♀️	0+	woman supervillain	criminal|evil|superpower|villain|woman
🧙	0+	mage	sorcerer|sorceress|witch|wizard
🧙‍♂️	0+	man mage	sorcerer|wizard
🧙‍♀️	0+	woman mage	sorceress|witch
🧚	0+	fairy	oberon|puck|titania
🧚‍♂️	0+	man fairy	oberon|puck
🧚‍♀️	0+	woman fairy	titania
🧛	0+	vampire	dracula|undead
🧛‍♂️	0+	man vampire	dracula|undead
🧛‍♀️	0+	woman vampire	undead
🧜	0+	merperson	mermaid|merman|merwoman
🧜‍♂️	0+	merman	triton
🧜‍♀️	0+	mermaid	merwoman
🧝	0+	elf	magical
🧝‍♂️	0+	man elf	magical
🧝‍♀️	0+	woman elf	magical
🧞	0	genie	djinn
🧞‍♂️	0	man genie	djinn
🧞‍♀️	0	woman genie	djinn
🧟	0	zombie	undead|walking dead
🧟‍♂️	0	man zombie	undead|walking dead
🧟‍♀️	0	woman zombie	undead|walking dead
🧌	0	troll	fairy tale|fantasy|monster
💆	0+	person getting massage	face|massage|salon
💆‍♂️	0+	man getting massage	face|man|massage
💆‍♀️	0+	woman getting massage	face|massage|woman
💇	0+	person getting haircut	barber|beauty|haircut|parlor
💇‍♂️	0+	man getting haircut	haircut|man
💇‍♀️	0+	woman getting haircut	haircut|woman
🚶	0+	person walking	hike|walk|walking
🚶‍♂️	0+	man walking	hike|man|walk
🚶‍♀️	0+	woman walking	hike|walk|woman
🚶‍➡️	0+	person walking facing right	
🚶‍♀️‍➡️	0+	woman walking facing right	
🚶‍♂️‍➡️	0+	man walking facing right	
🧍	0+	person standing	stand|standing
🧍‍♂️	0+	man standing	man|standing
🧍‍♀️	0+	woman standing	standing|woman
🧎	0+	person kneeling	kneel|kneeling
🧎‍♂️	0+	man kneeling	kneeling|man
🧎‍♀️	0+	woman kneeling	kneeling|woman
🧎‍➡️	0+	person kneeling facing right	
🧎‍♀️‍➡️	0+	woman kneeling facing right	
🧎‍♂️‍➡️	0+	man kneeling facing right	
🧑‍🦯	0+	person with white cane	accessibility|blind
🧑‍🦯‍➡️	0+	person with white cane facing right	
👨‍🦯	0+	man with white cane	accessibility|blind|man
👨‍🦯‍➡️	0+	man with white cane facing right	
👩‍🦯	0+	woman with white cane	accessibility|blind|woman
👩‍🦯‍➡️	0+	woman with white cane facing right	
🧑‍🦼	0+	person in motorized wheelchair	accessibility|wheelchair
🧑‍🦼‍➡️	0+	person in motorized wheelchair facing right	
👨‍🦼	0+	man in motorized wheelchair	accessibility|man|wheelchair
👨‍🦼‍➡️	0+	man in motorized wheelchair facing right	
👩‍🦼	0+	woman in motorized wheelchair	accessibility|wheelchair|woman
👩‍🦼‍➡️	0+	woman in motorized wheelchair facing right	
🧑‍🦽	0+	person in manual wheelchair	accessibility|wheelchair
🧑‍🦽‍➡️	0+	person in manual wheelchair facing right	
👨‍🦽	0+	man in manual wheelchair	accessibility|man|wheelchair
👨‍🦽‍➡️	0+	man in manual wheelchair facing right	
👩‍🦽	0+	woman in manual wheelchair	accessibility|wheelchair|woman
👩‍🦽‍➡️	0+	woman in manual wheelchair facing right	
🏃	0+	person running	marathon|running
🏃‍♂️	0+	man running	man|marathon|racing|running
🏃‍♀️	0+	woman running	marathon|racing|running|woman
🏃‍➡️	0+	person running facing right	
🏃‍♀️‍➡️	0+	woman running facing right	
🏃‍♂️‍➡️	0+	man running facing right	
💃	0+	woman dancing	dance|dancing|woman
🕺	0+	man dancing	dance|dancing|man
🕴️	0+	person in suit levitating	business|person|suit
👯	0	people with bunny ears	bunny ear|dancer|partying
👯‍♂️	0	men with bunny ears	bunny ear|dancer|men|partying
👯‍♀️	0	women with bunny ears	bunny ear|dancer|partying|women
🧖	0+	person in steamy room	sauna|steam room
🧖‍♂️	0+	man in steamy room	sauna|steam room
🧖‍♀️	0+	woman in steamy room	sauna|steam room
🧗	0+	person climbing	climber
🧗‍♂️	0+	man climbing	climber
🧗‍♀️	0+	woman climbing	climber
🤺	0	person fencing	fencer|fencing|sword
🏇	0+	horse racing	horse|jockey|racehorse|racing
⛷️	0	skier	ski|snow
🏂	0+	snowboarder	ski|snow|snowboard
🏌️	0+	person golfing	ball|golf
🏌️‍♂️	0+	man golfing	golf|man
🏌️‍♀️	0+	woman golfing	golf|woman
🏄	0+	person surfing	surfing
🏄‍♂️	0+	man surfing	man|surfing
🏄‍♀️	0+	woman surfing	surfing|woman
🚣	0+	person rowing boat	boat|rowboat
🚣‍♂️	0+	man rowing boat	boat|man|rowboat
🚣‍♀️	0+	woman rowing boat	boat|rowboat|woman
🏊	0+	person swimming	swim
🏊‍♂️	0+	man swimming	man|swim
🏊‍♀️	0+	woman swimming	swim|woman
⛹️	0+	person bouncing ball	ball
⛹️‍♂️	0+	man bouncing ball	ball|man
⛹️‍♀️	0+	woman bouncing ball	ball|woman
🏋️	0+	person lifting weights	lifter|weight
🏋️‍♂️	0+	man lifting weights	man|weight lifter
🏋️‍♀️	0+	woman lifting weights	weight lifter|woman
🚴	0+	person biking	bicycle|biking|cyclist
🚴‍♂️	0+	man biking	bicycle|biking|cyclist|man
🚴‍♀️	0+	woman biking	bicycle|biking|cyclist|woman
🚵	0+	person mountain biking	bicycle|bicyclist|bike|cyclist|mountain
🚵‍♂️	0+	man mountain biking	bicycle|bike|cyclist|man|mountain
🚵‍♀️	0+	woman mountain biking	bicycle|bike|biking|cyclist|mountain|woman
🤸	0+	person cartwheeling	cartwheel|gymnastics
🤸‍♂️	0+	man cartwheeling	cartwheel|gymnastics|man
🤸‍♀️	0+	woman cartwheeling	cartwheel|gymnastics|woman
🤼	0	people wrestling	wrestle|wrestler
🤼‍♂️	0	men wrestling	men|wrestle
🤼‍♀️	0	women wrestling	women|wrestle
🤽	0+	person playing water polo	polo|water
🤽‍♂️	0+	man playing water polo	man|water polo
🤽‍♀️	0+	woman playing water polo	water polo|woman
🤾	0+	person playing handball	ball|handball
🤾‍♂️	0+	man playing handball	handball|man
🤾‍♀️	0+	woman playing handball	handball|woman
🤹	0+	person juggling	balance|juggle|multitask|skill
🤹‍♂️	0+	man juggling	juggling|man|multitask
🤹‍♀️	0+	woman juggling	juggling|multitask|woman
🧘	0+	person in lotus position	meditation|yoga
🧘‍♂️	0+	man in lotus position	meditation|yoga
🧘‍♀️	0+	woman in lotus position	meditation|yoga
🛀	0+	person taking bath	bath|bathtub
🛌	0+	person in bed	good night|hotel|sleep
🧑‍🤝‍🧑	0+	people holding hands	couple|hand|hold|holding hands|person
👭	0+	women holding hands	couple|hand|holding hands|women
👫	0+	woman and man holding hands	couple|hand|hold|holding hands|man|woman
👬	0+	men holding hands	couple|gemini|holding hands|man|men|twins|zodiac
💏	0+	kiss	couple
👩‍❤️‍💋‍👨	0+	kiss: woman, man	couple|kiss|man|woman
👨‍❤️‍💋‍👨	0+	kiss: man, man	couple|kiss|man
👩‍❤️‍💋‍👩	0+	kiss: woman, woman	couple|kiss|woman
💑	0+	couple with heart	couple|love
👩‍❤️‍👨	0+	couple with heart: woman, man	couple|couple with heart|love|man|woman
👨‍❤️‍👨	0+	couple with heart: man, man	couple|couple with heart|love|man
👩‍❤️‍👩	0+	couple with heart: woman, woman	couple|couple with heart|love|woman
👨‍👩‍👦	0	family: man, woman, boy	boy|family|man|woman
👨‍👩‍👧	0	family: man, woman, girl	family|girl|man|woman
👨‍👩‍👧‍👦	0	family: man, woman, girl, boy	boy|family|girl|man|woman
👨‍👩‍👦‍👦	0	family: man, woman, boy, boy	boy|family|man|woman
👨‍👩‍👧‍👧	0	family: man, woman, girl, girl	family|girl|man|woman
👨‍👨‍👦	0	family: man, man, boy	boy|family|man
👨‍👨‍👧	0	family: man, man, girl	family|girl|man
👨‍👨‍👧‍👦	0	family: man, man, girl, boy	boy|family|girl|man
👨‍👨‍👦‍👦	0	family: man, man, boy, boy	boy|family|man
👨‍👨‍👧‍👧	0	family: man, man, girl, girl	family|girl|man
👩‍👩‍👦	0	family: woman, woman, boy	boy|family|woman
👩‍👩‍👧	0	family: woman, woman, girl	family|girl|woman
👩‍👩‍👧‍👦	0	family: woman, woman, girl, boy	boy|family|girl|woman
👩‍👩‍👦‍👦	0	family: woman, woman, boy, boy	boy|family|woman
👩‍👩‍👧‍👧	0	family: woman, woman, girl, girl	family|girl|woman
👨‍👦	0	family: man, boy	boy|family|man
👨‍👦‍👦	0	family: man, boy, boy	boy|family|man
👨‍👧	0	family: man, girl	family|girl|man
👨‍👧‍👦	0	family: man, girl, boy	boy|family|girl|man
👨‍👧‍👧	0	family: man, girl, girl	family|girl|man
👩‍👦	0	family: woman, boy	boy|family|woman
👩‍👦‍👦	0	family: woman, boy, boy	boy|family|woman
👩‍👧	0	family: woman, girl	family|girl|woman
👩‍👧‍👦	0	family: woman, girl, boy	boy|family|girl|woman
👩‍👧‍👧	0	family: woman, girl, girl	family|girl|woman
🗣️	0	speaking head	face|head|silhouette|speak|speaking
👤	0	bust in silhouette	bust|silhouette
👥	0	busts in silhouette	bust|silhouette
🫂	0	people hugging	goodbye|hello|hug|thanks
👪	0	family	
🧑‍🧑‍🧒	0	family: adult, adult, child	
🧑‍🧑‍🧒‍🧒	0	family: adult, adult, child, child	
🧑‍🧒	0	family: adult, child	
🧑‍🧒‍🧒	0	family: adult, child, child	
👣	0	footprints	clothing|footprint|print
🐵	1	monkey face	face|monkey
🐒	1	monkey	
🦍	1	gorilla	
🦧	1	orangutan	ape
🐶	1	dog face	dog|face|pet
🐕	1	dog	pet
🦮	1	guide dog	accessibility|blind|guide
🐕‍🦺	1	service dog	accessibility|assistance|dog|service
🐩	1	poodle	dog
🐺	1	wolf	face
🦊	1	fox	face
🦝	1	raccoon	curious|sly
🐱	1	cat face	cat|face|pet
🐈	1	cat	pet
🐈‍⬛	1	black cat	black|cat|unlucky
🦁	1	lion	face|leo|zodiac
🐯	1	tiger face	face|tiger
🐅	1	tiger	
🐆	1	leopard	
🐴	1	horse face	face|horse
🫎	1	moose	animal|antlers|elk|mammal
🫏	1	donkey	animal|ass|burro|mammal|mule|stubborn
🐎	1	horse	equestrian|racehorse|racing
🦄	1	unicorn	face
🦓	1	zebra	stripe
🦌	1	deer	
🦬	1	bison	buffalo|herd|wisent
🐮	1	cow face	cow|face
🐂	1	ox	bull|taurus|zodiac
🐃	1	water buffalo	buffalo|water
🐄	1	cow	
🐷	1	pig face	face|pig
🐖	1	pig	sow
🐗	1	boar	pig
🐽	1	pig nose	face|nose|pig
🐏	1	ram	aries|male|sheep|zodiac
🐑	1	ewe	female|sheep
🐐	1	goat	capricorn|zodiac
🐪	1	camel	dromedary|hump
🐫	1	two-hump camel	bactrian|camel|hump
🦙	1	llama	alpaca|guanaco|vicuña|wool
🦒	1	giraffe	spots
🐘	1	elephant	
🦣	1	mammoth	extinction|large|tusk|woolly
🦏	1	rhinoceros	
🦛	1	hippopotamus	hippo
🐭	1	mouse face	face|mouse
🐁	1	mouse	
🐀	1	rat	
🐹	1	hamster	face|pet
🐰	1	rabbit face	bunny|face|pet|rabbit
🐇	1	rabbit	bunny|pet
🐿️	1	chipmunk	squirrel
🦫	1	beaver	dam
🦔	1	hedgehog	spiny
🦇	1	bat	vampire
🐻	1	bear	face
🐻‍❄️	1	polar bear	arctic|bear|white
🐨	1	koala	face|marsupial
🐼	1	panda	face
🦥	1	sloth	lazy|slow
🦦	1	otter	fishing|playful
🦨	1	skunk	stink
🦘	1	kangaroo	joey|jump|marsupial
🦡	1	badger	honey badger|pester
🐾	1	paw prints	feet|paw|print
🦃	1	turkey	bird
🐔	1	chicken	bird
🐓	1	rooster	bird
🐣	1	hatching chick	baby|bird|chick|hatching
🐤	1	baby chick	baby|bird|chick
🐥	1	front-facing baby chick	baby|bird|chick
🐦	1	bird	
🐧	1	penguin	bird
🕊️	1	dove	bird|fly|peace
🦅	1	eagle	bird
🦆	1	duck	bird
🦢	1	swan	bird|cygnet|ugly duckling
🦉	1	owl	bird|wise
🦤	1	dodo	extinction|large|mauritius
🪶	1	feather	bird|flight|light|plumage
🦩	1	flamingo	flamboyant|tropical
🦚	1	peacock	bird|ostentatious|peahen|proud
🦜	1	parrot	bird|pirate|talk
🪽	1	wing	angelic|aviation|bird|flying|mythology
🐦‍⬛	1	black bird	bird|black|crow|raven|rook
🪿	1	goose	bird|fowl|honk|silly
🐦‍🔥	1	phoenix	fantasy|firebird|rebirth|reincarnation
🐸	1	frog	face
🐊	1	crocodile	
🐢	1	turtle	terrapin|tortoise
🦎	1	lizard	reptile
🐍	1	snake	bearer|ophiuchus|serpent|zodiac
🐲	1	dragon face	dragon|face|fairy tale
🐉	1	dragon	fairy tale
🦕	1	sauropod	brachiosaurus|brontosaurus|diplodocus
🦖	1	t-rex	tyrannosaurus rex
🐳	1	spouting whale	face|spouting|whale
🐋	1	whale	
🐬	1	dolphin	flipper
🦭	1	seal	sea lion
🐟	1	fish	pisces|zodiac
🐠	1	tropical fish	fish|tropical
🐡	1	blowfish	fish
🦈	1	shark	fish
🐙	1	octopus	
🐚	1	spiral shell	shell|spiral
🪸	1	coral	ocean|reef
🪼	1	jellyfish	burn|invertebrate|jelly|marine|ouch|stinger
🐌	1	snail	
🦋	1	butterfly	insect|pretty
🐛	1	bug	insect
🐜	1	ant	insect
🐝	1	honeybee	bee|insect
🪲	1	beetle	bug|insect
🐞	1	lady beetle	beetle|insect|ladybird|ladybug
🦗	1	cricket	grasshopper
🪳	1	cockroach	insect|pest|roach
🕷️	1	spider	insect
🕸️	1	spider web	spider|web
🦂	1	scorpion	scorpio|zodiac
🦟	1	mosquito	disease|fever|malaria|pest|virus
🪰	1	fly	disease|maggot|pest|rotting
🪱	1	worm	annelid|earthworm|parasite
🦠	1	microbe	amoeba|bacteria|virus
💐	1	bouquet	flower
🌸	1	cherry blossom	blossom|cherry|flower
💮	1	white flower	flower
🪷	1	lotus	buddhism|flower|hinduism|purity
🏵️	1	rosette	plant
🌹	1	rose	flower
🥀	1	wilted flower	flower|wilted
🌺	1	hibiscus	flower
🌻	1	sunflower	flower|sun
🌼	1	blossom	flower
🌷	1	tulip	flower
🪻	1	hyacinth	bluebonnet|flower|lavender|lupine|snapdragon
🌱	1	seedling	young
🪴	1	potted plant	boring|grow|house|nurturing|plant|useless
🌲	1	evergreen tree	tree
🌳	1	deciduous tree	deciduous|shedding|tree
🌴	1	palm tree	palm|tree
🌵	1	cactus	plant
🌾	1	sheaf of rice	ear|grain|rice
🌿	1	herb	leaf
☘️	1	shamrock	plant
🍀	1	four leaf clover	4|clover|four|four-leaf clover|leaf
🍁	1	maple leaf	falling|leaf|maple
🍂	1	fallen leaf	falling|leaf
🍃	1	leaf fluttering in wind	blow|flutter|leaf|wind
🪹	1	empty nest	nesting
🪺	1	nest with eggs	nesting
🍄	1	mushroom	toadstool
🍇	2	grapes	fruit|grape
🍈	2	melon	fruit
🍉	2	watermelon	fruit
🍊	2	tangerine	fruit|orange
🍋	2	lemon	citrus|fruit
🍋‍🟩	2	lime	citrus|fruit|tropical
🍌	2	banana	fruit
🍍	2	pineapple	fruit
🥭	2	mango	fruit|tropical
🍎	2	red apple	apple|fruit|red
🍏	2	green apple	apple|fruit|green
🍐	2	pear	fruit
🍑	2	peach	fruit
🍒	2	cherries	berries|cherry|fruit|red
🍓	2	strawberry	berry|fruit
🫐	2	blueberries	berry|bilberry|blue|blueberry
🥝	2	kiwi fruit	food|fruit|kiwi
🍅	2	tomato	fruit|vegetable
🫒	2	olive	food
🥥	2	coconut	palm|piña colada
🥑	2	avocado	food|fruit
🍆	2	eggplant	aubergine|vegetable
🥔	2	potato	food|vegetable
🥕	2	carrot	food|vegetable
🌽	2	ear of corn	corn|ear|maize|maze
🌶️	2	hot pepper	hot|pepper
🫑	2	bell pepper	capsicum|pepper|vegetable
🥒	2	cucumber	food|pickle|vegetable
🥬	2	leafy green	bok choy|cabbage|kale|lettuce
🥦	2	broccoli	wild cabbage
🧄	2	garlic	flavoring
🧅	2	onion	flavoring
🥜	2	peanuts	food|nut|peanut|vegetable
🫘	2	beans	food|kidney|legume
🌰	2	chestnut	plant
🫚	2	ginger root	beer|root|spice
🫛	2	pea pod	beans|edamame|legume|pea|pod|vegetable
🍄‍🟫	2	brown mushroom	food|fungus|nature|vegetable
🍞	2	bread	loaf
🥐	2	croissant	bread|breakfast|food|french|roll
🥖	2	baguette bread	baguette|bread|food|french
🫓	2	flatbread	arepa|lavash|naan|pita
🥨	2	pretzel	twisted
🥯	2	bagel	bakery|breakfast|schmear
🥞	2	pancakes	breakfast|crêpe|food|hotcake|pancake
🧇	2	waffle	breakfast|indecisive|iron
🧀	2	cheese wedge	cheese
🍖	2	meat on bone	bone|meat
🍗	2	poultry leg	bone|chicken|drumstick|leg|poultry
🥩	2	cut of meat	chop|lambchop|porkchop|steak
🥓	2	bacon	breakfast|food|meat
🍔	2	hamburger	burger
🍟	2	french fries	french|fries
🍕	2	pizza	cheese|slice
🌭	2	hot dog	frankfurter|hotdog|sausage
🥪	2	sandwich	bread
🌮	2	taco	mexican
🌯	2	burrito	mexican|wrap
🫔	2	tamale	mexican|wrapped
🥙	2	stuffed flatbread	falafel|flatbread|food|gyro|kebab|stuffed
🧆	2	falafel	chickpea|meatball
🥚	2	egg	breakfast|food
🍳	2	cooking	breakfast|egg|frying|pan
🥘	2	shallow pan of food	casserole|food|paella|pan|shallow
🍲	2	pot of food	pot|stew
🫕	2	fondue	cheese|chocolate|melted|pot|swiss
🥣	2	bowl with spoon	breakfast|cereal|congee
🥗	2	green salad	food|green|salad
🍿	2	popcorn	
🧈	2	butter	dairy
🧂	2	salt	condiment|shaker
🥫	2	canned food	can
🍱	2	bento box	bento|box
🍘	2	rice cracker	cracker|rice
🍙	2	rice ball	ball|japanese|rice
🍚	2	cooked rice	cooked|rice
🍛	2	curry rice	curry|rice
🍜	2	steaming bowl	bowl|noodle|ramen|steaming
🍝	2	spaghetti	pasta
🍠	2	roasted sweet potato	potato|roasted|sweet
🍢	2	oden	kebab|seafood|skewer|stick
🍣	2	sushi	
🍤	2	fried shrimp	fried|prawn|shrimp|tempura
🍥	2	fish cake with swirl	cake|fish|pastry|swirl
🥮	2	moon cake	autumn|festival|yuèbǐng
🍡	2	dango	dessert|japanese|skewer|stick|sweet
🥟	2	dumpling	empanada|gyōza|jiaozi|pierogi|potsticker
🥠	2	fortune cookie	prophecy
🥡	2	takeout box	oyster pail
🦀	2	crab	cancer|zodiac
🦞	2	lobster	bisque|claws|seafood
🦐	2	shrimp	food|shellfish|small
🦑	2	squid	food|molusc
🦪	2	oyster	diving|pearl
🍦	2	soft ice cream	cream|dessert|ice|icecream|soft|sweet
🍧	2	shaved ice	dessert|ice|shaved|sweet
🍨	2	ice cream	cream|dessert|ice|sweet
🍩	2	doughnut	breakfast|dessert|donut|sweet
🍪	2	cookie	dessert|sweet
🎂	2	birthday cake	birthday|cake|celebration|dessert|pastry|sweet
🍰	2	shortcake	cake|dessert|pastry|slice|sweet
🧁	2	cupcake	bakery|sweet
🥧	2	pie	filling|pastry
🍫	2	chocolate bar	bar|chocolate|dessert|sweet
🍬	2	candy	dessert|sweet
🍭	2	lollipop	candy|dessert|sweet
🍮	2	custard	dessert|pudding|sweet
🍯	2	honey pot	honey|honeypot|pot|sweet
🍼	2	baby bottle	baby|bottle|drink|milk
🥛	2	glass of milk	drink|glass|milk
☕	2	hot beverage	beverage|coffee|drink|hot|steaming|tea
🫖	2	teapot	drink|pot|tea
🍵	2	teacup without handle	beverage|cup|drink|tea|teacup
🍶	2	sake	bar|beverage|bottle|cup|drink
🍾	2	bottle with popping cork	bar|bottle|cork|drink|popping
🍷	2	wine glass	bar|beverage|drink|glass|wine
🍸	2	cocktail glass	bar|cocktail|drink|glass
🍹	2	tropical drink	bar|drink|tropical
🍺	2	beer mug	bar|beer|drink|mug
🍻	2	clinking beer mugs	bar|beer|clink|drink|mug
🥂	2	clinking glasses	celebrate|clink|drink|glass
🥃	2	tumbler glass	glass|liquor|shot|tumbler|whisky
🫗	2	pouring liquid	drink|empty|glass|spill
🥤	2	cup with straw	juice|soda
🧋	2	bubble tea	bubble|milk|pearl|tea
🧃	2	beverage box	beverage|box|juice|straw|sweet
🧉	2	mate	drink
🧊	2	ice	cold|ice cube|iceberg
🥢	2	chopsticks	hashi
🍽️	2	fork and knife with plate	cooking|fork|knife|plate
🍴	2	fork and knife	cooking|cutlery|fork|knife
🥄	2	spoon	tableware
🔪	2	kitchen knife	cooking|hocho|knife|tool|weapon
🫙	2	jar	condiment|container|empty|sauce|store
🏺	2	amphora	aquarius|cooking|drink|jug|zodiac
🌍	4	globe showing europe-africa	africa|earth|europe|globe|world
🌎	4	globe showing americas	americas|earth|globe|world
🌏	4	globe showing asia-australia	asia|australia|earth|globe|world
🌐	4	globe with meridians	earth|globe|meridians|world
🗺️	4	world map	map|world
🗾	4	map of japan	japan|map
🧭	4	compass	magnetic|navigation|orienteering
🏔️	4	snow-capped mountain	cold|mountain|snow
⛰️	4	mountain	
🌋	4	volcano	eruption|mountain
🗻	4	mount fuji	fuji|mountain
🏕️	4	camping	
🏖️	4	beach with umbrella	beach|umbrella
🏜️	4	desert	
🏝️	4	desert island	desert|island
🏞️	4	national park	park
🏟️	4	stadium	
🏛️	4	classical building	classical
🏗️	4	building construction	construction
🧱	4	brick	bricks|clay|mortar|wall
🪨	4	rock	boulder|heavy|solid|stone
🪵	4	wood	log|lumber|timber
🛖	4	hut	house|roundhouse|yurt
🏘️	4	houses	
🏚️	4	derelict house	derelict|house
🏠	4	house	home
🏡	4	house with garden	garden|home|house
🏢	4	office building	building
🏣	4	japanese post office	japanese|post
🏤	4	post office	european|post
🏥	4	hospital	doctor|medicine
🏦	4	bank	building
🏨	4	hotel	building
🏩	4	love hotel	hotel|love
🏪	4	convenience store	convenience|store
🏫	4	school	building
🏬	4	department store	department|store
🏭	4	factory	building
🏯	4	japanese castle	castle|japanese
🏰	4	castle	european
💒	4	wedding	chapel|romance
🗼	4	tokyo tower	tokyo|tower
🗽	4	statue of liberty	liberty|statue
⛪	4	church	christian|cross|religion
🕌	4	mosque	islam|muslim|religion
🛕	4	hindu temple	hindu|temple
🕍	4	synagogue	jew|jewish|religion|temple
⛩️	4	shinto shrine	religion|shinto|shrine
🕋	4	kaaba	islam|muslim|religion
⛲	4	fountain	
⛺	4	tent	camping
🌁	4	foggy	fog
🌃	4	night with stars	night|star
🏙️	4	cityscape	city
🌄	4	sunrise over mountains	morning|mountain|sun|sunrise
🌅	4	sunrise	morning|sun
🌆	4	cityscape at dusk	city|dusk|evening|landscape|sunset
🌇	4	sunset	dusk|sun
🌉	4	bridge at night	bridge|night
♨️	4	hot springs	hot|hotsprings|springs|steaming
🎠	4	carousel horse	carousel|horse
🛝	4	playground slide	amusement park|play|theme park
🎡	4	ferris wheel	amusement park|ferris|theme park|wheel
🎢	4	roller coaster	amusement park|coaster|roller|theme park
💈	4	barber pole	barber|haircut|pole
🎪	4	circus tent	circus|tent
🚂	4	locomotive	engine|railway|steam|train
🚃	4	railway car	car|electric|railway|train|tram|trolleybus
🚄	4	high-speed train	railway|shinkansen|speed|train
🚅	4	bullet train	bullet|railway|shinkansen|speed|train
🚆	4	train	railway
🚇	4	metro	subway
🚈	4	light rail	railway
🚉	4	station	railway|train
🚊	4	tram	trolleybus
🚝	4	monorail	vehicle
🚞	4	mountain railway	car|mountain|railway
🚋	4	tram car	car|tram|trolleybus
🚌	4	bus	vehicle
🚍	4	oncoming bus	bus|oncoming
🚎	4	trolleybus	bus|tram|trolley
🚐	4	minibus	bus
🚑	4	ambulance	vehicle
🚒	4	fire engine	engine|fire|truck
🚓	4	police car	car|patrol|police
🚔	4	oncoming police car	car|oncoming|police
🚕	4	taxi	vehicle
🚖	4	oncoming taxi	oncoming|taxi
🚗	4	automobile	car
🚘	4	oncoming automobile	automobile|car|oncoming
🚙	4	sport utility vehicle	recreational|sport utility
🛻	4	pickup truck	pick-up|pickup|truck
🚚	4	delivery truck	delivery|truck
🚛	4	articulated lorry	lorry|semi|truck
🚜	4	tractor	vehicle
🏎️	4	racing car	car|racing
🏍️	4	motorcycle	racing
🛵	4	motor scooter	motor|scooter
🦽	4	manual wheelchair	accessibility
🦼	4	motorized wheelchair	accessibility
🛺	4	auto rickshaw	tuk tuk
🚲	4	bicycle	bike
🛴	4	kick scooter	kick|scooter
🛹	4	skateboard	board
🛼	4	roller skate	roller|skate
🚏	4	bus stop	bus|stop
🛣️	4	motorway	highway|road
🛤️	4	railway track	railway|train
🛢️	4	oil drum	drum|oil
⛽	4	fuel pump	diesel|fuel|fuelpump|gas|pump|station
🛞	4	wheel	circle|tire|turn
🚨	4	police car light	beacon|car|light|police|revolving
🚥	4	horizontal traffic light	light|signal|traffic
🚦	4	vertical traffic light	light|signal|traffic
🛑	4	stop sign	octagonal|sign|stop
🚧	4	construction	barrier
⚓	4	anchor	ship|tool
🛟	4	ring buoy	float|life preserver|life saver|rescue|safety
⛵	4	sailboat	boat|resort|sea|yacht
🛶	4	canoe	boat
🚤	4	speedboat	boat
🛳️	4	passenger ship	passenger|ship
⛴️	4	ferry	boat|passenger
🛥️	4	motor boat	boat|motorboat
🚢	4	ship	boat|passenger
✈️	4	airplane	aeroplane
🛩️	4	small airplane	aeroplane|airplane
🛫	4	airplane departure	aeroplane|airplane|check-in|departure|departures
🛬	4	airplane arrival	aeroplane|airplane|arrivals|arriving|landing
🪂	4	parachute	hang-glide|parasail|skydive
💺	4	seat	chair
🚁	4	helicopter	vehicle
🚟	4	suspension railway	railway|suspension
🚠	4	mountain cableway	cable|gondola|mountain
🚡	4	aerial tramway	aerial|cable|car|gondola|tramway
🛰️	4	satellite	space
🚀	4	rocket	space
🛸	4	flying saucer	ufo
🛎️	4	bellhop bell	bell|bellhop|hotel
🧳	4	luggage	packing|travel
⌛	4	hourglass done	sand|timer
⏳	4	hourglass not done	hourglass|sand|timer
⌚	4	watch	clock
⏰	4	alarm clock	alarm|clock
⏱️	4	stopwatch	clock
⏲️	4	timer clock	clock|timer
🕰️	4	mantelpiece clock	clock
🕛	4	twelve o’clock	00|12|12:00|clock|o’clock|twelve
🕧	4	twelve-thirty	12|12:30|clock|thirty|twelve
🕐	4	one o’clock	00|1|1:00|clock|o’clock|one
🕜	4	one-thirty	1|1:30|clock|one|thirty
🕑	4	two o’clock	00|2|2:00|clock|o’clock|two
🕝	4	two-thirty	2|2:30|clock|thirty|two
🕒	4	three o’clock	00|3|3:00|clock|o’clock|three
🕞	4	three-thirty	3|3:30|clock|thirty|three
🕓	4	four o’clock	00|4|4:00|clock|four|o’clock
🕟	4	four-thirty	4|4:30|clock|four|thirty
🕔	4	five o’clock	00|5|5:00|clock|five|o’clock
🕠	4	five-thirty	5|5:30|clock|five|thirty
🕕	4	six o’clock	00|6|6:00|clock|o’clock|six
🕡	4	six-thirty	6|6:30|clock|six|thirty
🕖	4	seven o’clock	00|7|7:00|clock|o’clock|seven
🕢	4	seven-thirty	7|7:30|clock|seven|thirty
🕗	4	eight o’clock	00|8|8:00|clock|eight|o’clock
🕣	4	eight-thirty	8|8:30|clock|eight|thirty
🕘	4	nine o’clock	00|9|9:00|clock|nine|o’clock
🕤	4	nine-thirty	9|9:30|clock|nine|thirty
🕙	4	ten o’clock	00|10|10:00|clock|o’clock|ten
🕥	4	ten-thirty	10|10:30|clock|ten|thirty
🕚	4	eleven o’clock	00|11|11:00|clock|eleven|o’clock
🕦	4	eleven-thirty	11|11:30|clock|eleven|thirty
🌑	4	new moon	dark|moon
🌒	4	waxing crescent moon	crescent|moon|waxing
🌓	4	first quarter moon	moon|quarter
🌔	4	waxing gibbous moon	gibbous|moon|waxing
🌕	4	full moon	full|moon
🌖	4	waning gibbous moon	gibbous|moon|waning
🌗	4	last quarter moon	moon|quarter
🌘	4	waning crescent moon	crescent|moon|waning
🌙	4	crescent moon	crescent|moon
🌚	4	new moon face	face|moon
🌛	4	first quarter moon face	face|moon|quarter
🌜	4	last quarter moon face	face|moon|quarter
🌡️	4	thermometer	weather
☀️	4	sun	bright|rays|sunny
🌝	4	full moon face	bright|face|full|moon
🌞	4	sun with face	bright|face|sun
🪐	4	ringed planet	saturn|saturnine
⭐	4	star	
🌟	4	glowing star	glittery|glow|shining|sparkle|star
🌠	4	shooting star	falling|shooting|star
🌌	4	milky way	space
☁️	4	cloud	weather
⛅	4	sun behind cloud	cloud|sun
⛈️	4	cloud with lightning and rain	cloud|rain|thunder
🌤️	4	sun behind small cloud	cloud|sun
🌥️	4	sun behind large cloud	cloud|sun
🌦️	4	sun behind rain cloud	cloud|rain|sun
🌧️	4	cloud with rain	cloud|rain
🌨️	4	cloud with snow	cloud|cold|snow
🌩️	4	cloud with lightning	cloud|lightning
🌪️	4	tornado	cloud|whirlwind
🌫️	4	fog	cloud
🌬️	4	wind face	blow|cloud|face|wind
🌀	4	cyclone	dizzy|hurricane|twister|typhoon
🌈	4	rainbow	rain
🌂	4	closed umbrella	clothing|rain|umbrella
☂️	4	umbrella	clothing|rain
☔	4	umbrella with rain drops	clothing|drop|rain|umbrella
⛱️	4	umbrella on ground	rain|sun|umbrella
⚡	4	high voltage	danger|electric|lightning|voltage|zap
❄️	4	snowflake	cold|snow
☃️	4	snowman	cold|snow
⛄	4	snowman without snow	cold|snow|snowman
☄️	4	comet	space
🔥	4	fire	flame|tool
💧	4	droplet	cold|comic|drop|sweat
🌊	4	water wave	ocean|water|wave
🎃	3	jack-o-lantern	celebration|halloween|jack|lantern
🎄	3	christmas tree	celebration|christmas|tree
🎆	3	fireworks	celebration
🎇	3	sparkler	celebration|fireworks|sparkle
🧨	3	firecracker	dynamite|explosive|fireworks
✨	3	sparkles	*|sparkle|star
🎈	3	balloon	celebration
🎉	3	party popper	celebration|party|popper|tada
🎊	3	confetti ball	ball|celebration|confetti
🎋	3	tanabata tree	banner|celebration|japanese|tree
🎍	3	pine decoration	bamboo|celebration|japanese|pine
🎎	3	japanese dolls	celebration|doll|festival|japanese
🎏	3	carp streamer	carp|celebration|streamer
🎐	3	wind chime	bell|celebration|chime|wind
🎑	3	moon viewing ceremony	celebration|ceremony|moon
🧧	3	red envelope	gift|good luck|hóngbāo|lai see|money
🎀	3	ribbon	celebration
🎁	3	wrapped gift	box|celebration|gift|present|wrapped
🎗️	3	reminder ribbon	celebration|reminder|ribbon
🎟️	3	admission tickets	admission|ticket
🎫	3	ticket	admission
🎖️	3	military medal	celebration|medal|military
🏆	3	trophy	prize
🏅	3	sports medal	medal
🥇	3	1st place medal	first|gold|medal
🥈	3	2nd place medal	medal|second|silver
🥉	3	3rd place medal	bronze|medal|third
⚽	3	soccer ball	ball|football|soccer
⚾	3	baseball	ball
🥎	3	softball	ball|glove|underarm
🏀	3	basketball	ball|hoop
🏐	3	volleyball	ball|game
🏈	3	american football	american|ball|football
🏉	3	rugby football	ball|football|rugby
🎾	3	tennis	ball|racquet
🥏	3	flying disc	ultimate
🎳	3	bowling	ball|game
🏏	3	cricket game	ball|bat|game
🏑	3	field hockey	ball|field|game|hockey|stick
🏒	3	ice hockey	game|hockey|ice|puck|stick
🥍	3	lacrosse	ball|goal|stick
🏓	3	ping pong	ball|bat|game|paddle|table tennis
🏸	3	badminton	birdie|game|racquet|shuttlecock
🥊	3	boxing glove	boxing|glove
🥋	3	martial arts uniform	judo|karate|martial arts|taekwondo|uniform
🥅	3	goal net	goal|net
⛳	3	flag in hole	golf|hole
⛸️	3	ice skate	ice|skate
🎣	3	fishing pole	fish|pole
🤿	3	diving mask	diving|scuba|snorkeling
🎽	3	running shirt	athletics|running|sash|shirt
🎿	3	skis	ski|snow
🛷	3	sled	sledge|sleigh
🥌	3	curling stone	game|rock""",
    """🎯	3	bullseye	dart|direct hit|game|hit|target
🪀	3	yo-yo	fluctuate|toy
🪁	3	kite	fly|soar
🔫	3	water pistol	gun|handgun|pistol|revolver|tool|water|weapon
🎱	3	pool 8 ball	8|ball|billiard|eight|game
🔮	3	crystal ball	ball|crystal|fairy tale|fantasy|fortune|tool
🪄	3	magic wand	magic|witch|wizard
🎮	3	video game	controller|game
🕹️	3	joystick	game|video game
🎰	3	slot machine	game|slot
🎲	3	game die	dice|die|game
🧩	3	puzzle piece	clue|interlocking|jigsaw|piece|puzzle
🧸	3	teddy bear	plaything|plush|stuffed|toy
🪅	3	piñata	celebration|party
🪩	3	mirror ball	dance|disco|glitter|party
🪆	3	nesting dolls	doll|nesting|russia
♠️	3	spade suit	card|game
♥️	3	heart suit	card|game
♦️	3	diamond suit	card|game
♣️	3	club suit	card|game
♟️	3	chess pawn	chess|dupe|expendable
🃏	3	joker	card|game|wildcard
🀄	3	mahjong red dragon	game|mahjong|red
🎴	3	flower playing cards	card|flower|game|japanese|playing
🎭	3	performing arts	art|mask|performing|theater|theatre
🖼️	3	framed picture	art|frame|museum|painting|picture
🎨	3	artist palette	art|museum|painting|palette
🧵	3	thread	needle|sewing|spool|string
🪡	3	sewing needle	embroidery|needle|sewing|stitches|sutures|tailoring
🧶	3	yarn	ball|crochet|knit
🪢	3	knot	rope|tangled|tie|twine|twist
👓	5	glasses	clothing|eye|eyeglasses|eyewear
🕶️	5	sunglasses	dark|eye|eyewear|glasses
🥽	5	goggles	eye protection|swimming|welding
🥼	5	lab coat	doctor|experiment|scientist
🦺	5	safety vest	emergency|safety|vest
👔	5	necktie	clothing|tie
👕	5	t-shirt	clothing|shirt|tshirt
👖	5	jeans	clothing|pants|trousers
🧣	5	scarf	neck
🧤	5	gloves	hand
🧥	5	coat	jacket
🧦	5	socks	stocking
👗	5	dress	clothing
👘	5	kimono	clothing
🥻	5	sari	clothing|dress
🩱	5	one-piece swimsuit	bathing suit
🩲	5	briefs	bathing suit|one-piece|swimsuit|underwear
🩳	5	shorts	bathing suit|pants|underwear
👙	5	bikini	clothing|swim
👚	5	woman’s clothes	clothing|woman
🪭	5	folding hand fan	cooling|dance|fan|flutter|hot|shy
👛	5	purse	clothing|coin
👜	5	handbag	bag|clothing|purse
👝	5	clutch bag	bag|clothing|pouch
🛍️	5	shopping bags	bag|hotel|shopping
🎒	5	backpack	bag|rucksack|satchel|school
🩴	5	thong sandal	beach sandals|sandals|thong sandals|thongs|zōri
👞	5	man’s shoe	clothing|man|shoe
👟	5	running shoe	athletic|clothing|shoe|sneaker
🥾	5	hiking boot	backpacking|boot|camping|hiking
🥿	5	flat shoe	ballet flat|slip-on|slipper
👠	5	high-heeled shoe	clothing|heel|shoe|woman
👡	5	woman’s sandal	clothing|sandal|shoe|woman
🩰	5	ballet shoes	ballet|dance
👢	5	woman’s boot	boot|clothing|shoe|woman
🪮	5	hair pick	afro|comb|hair|pick
👑	5	crown	clothing|king|queen
👒	5	woman’s hat	clothing|hat|woman
🎩	5	top hat	clothing|hat|top|tophat
🎓	5	graduation cap	cap|celebration|clothing|graduation|hat
🧢	5	billed cap	baseball cap
🪖	5	military helmet	army|helmet|military|soldier|warrior
⛑️	5	rescue worker’s helmet	aid|cross|face|hat|helmet
📿	5	prayer beads	beads|clothing|necklace|prayer|religion
💄	5	lipstick	cosmetics|makeup
💍	5	ring	diamond
💎	5	gem stone	diamond|gem|jewel
🔇	5	muted speaker	mute|quiet|silent|speaker
🔈	5	speaker low volume	soft
🔉	5	speaker medium volume	medium
🔊	5	speaker high volume	loud
📢	5	loudspeaker	loud|public address
📣	5	megaphone	cheering
📯	5	postal horn	horn|post|postal
🔔	5	bell	
🔕	5	bell with slash	bell|forbidden|mute|quiet|silent
🎼	5	musical score	music|score
🎵	5	musical note	music|note
🎶	5	musical notes	music|note|notes
🎙️	5	studio microphone	mic|microphone|music|studio
🎚️	5	level slider	level|music|slider
🎛️	5	control knobs	control|knobs|music
🎤	5	microphone	karaoke|mic
🎧	5	headphone	earbud
📻	5	radio	video
🎷	5	saxophone	instrument|music|sax
🪗	5	accordion	concertina|squeeze box
🎸	5	guitar	instrument|music
🎹	5	musical keyboard	instrument|keyboard|music|piano
🎺	5	trumpet	instrument|music
🎻	5	violin	instrument|music
🪕	5	banjo	music|stringed
🥁	5	drum	drumsticks|music
🪘	5	long drum	beat|conga|drum|rhythm
🪇	5	maracas	instrument|music|percussion|rattle|shake
🪈	5	flute	fife|music|pipe|recorder|woodwind
📱	5	mobile phone	cell|mobile|phone|telephone
📲	5	mobile phone with arrow	arrow|cell|mobile|phone|receive
☎️	5	telephone	phone
📞	5	telephone receiver	phone|receiver|telephone
📟	5	pager	
📠	5	fax machine	fax
🔋	5	battery	
🪫	5	low battery	electronic|low energy
🔌	5	electric plug	electric|electricity|plug
💻	5	laptop	computer|pc|personal
🖥️	5	desktop computer	computer|desktop
🖨️	5	printer	computer
⌨️	5	keyboard	computer
🖱️	5	computer mouse	computer
🖲️	5	trackball	computer
💽	5	computer disk	computer|disk|minidisk|optical
💾	5	floppy disk	computer|disk|floppy
💿	5	optical disk	cd|computer|disk|optical
📀	5	dvd	blu-ray|computer|disk|optical
🧮	5	abacus	calculation
🎥	5	movie camera	camera|cinema|movie
🎞️	5	film frames	cinema|film|frames|movie
📽️	5	film projector	cinema|film|movie|projector|video
🎬	5	clapper board	clapper|movie
📺	5	television	tv|video
📷	5	camera	video
📸	5	camera with flash	camera|flash|video
📹	5	video camera	camera|video
📼	5	videocassette	tape|vhs|video
🔍	5	magnifying glass tilted left	glass|magnifying|search|tool
🔎	5	magnifying glass tilted right	glass|magnifying|search|tool
🕯️	5	candle	light
💡	5	light bulb	bulb|comic|electric|idea|light
🔦	5	flashlight	electric|light|tool|torch
🏮	5	red paper lantern	bar|lantern|light|red
🪔	5	diya lamp	diya|lamp|oil
📔	5	notebook with decorative cover	book|cover|decorated|notebook
📕	5	closed book	book|closed
📖	5	open book	book|open
📗	5	green book	book|green
📘	5	blue book	blue|book
📙	5	orange book	book|orange
📚	5	books	book
📓	5	notebook	
📒	5	ledger	notebook
📃	5	page with curl	curl|document|page
📜	5	scroll	paper
📄	5	page facing up	document|page
📰	5	newspaper	news|paper
🗞️	5	rolled-up newspaper	news|newspaper|paper|rolled
📑	5	bookmark tabs	bookmark|mark|marker|tabs
🔖	5	bookmark	mark
🏷️	5	label	
💰	5	money bag	bag|dollar|money|moneybag
🪙	5	coin	gold|metal|money|silver|treasure
💴	5	yen banknote	banknote|bill|currency|money|note|yen
💵	5	dollar banknote	banknote|bill|currency|dollar|money|note
💶	5	euro banknote	banknote|bill|currency|euro|money|note
💷	5	pound banknote	banknote|bill|currency|money|note|pound
💸	5	money with wings	banknote|bill|fly|money|wings
💳	5	credit card	card|credit|money
🧾	5	receipt	accounting|bookkeeping|evidence|proof
💹	5	chart increasing with yen	chart|graph|growth|money|yen
✉️	5	envelope	email|letter
📧	5	e-mail	email|letter|mail
📨	5	incoming envelope	e-mail|email|envelope|incoming|letter|receive
📩	5	envelope with arrow	arrow|e-mail|email|envelope|outgoing
📤	5	outbox tray	box|letter|mail|outbox|sent|tray
📥	5	inbox tray	box|inbox|letter|mail|receive|tray
📦	5	package	box|parcel
📫	5	closed mailbox with raised flag	closed|mail|mailbox|postbox
📪	5	closed mailbox with lowered flag	closed|lowered|mail|mailbox|postbox
📬	5	open mailbox with raised flag	mail|mailbox|open|postbox
📭	5	open mailbox with lowered flag	lowered|mail|mailbox|open|postbox
📮	5	postbox	mail|mailbox
🗳️	5	ballot box with ballot	ballot|box
✏️	5	pencil	
✒️	5	black nib	nib|pen
🖋️	5	fountain pen	fountain|pen
🖊️	5	pen	ballpoint
🖌️	5	paintbrush	painting
🖍️	5	crayon	
📝	5	memo	pencil
💼	5	briefcase	
📁	5	file folder	file|folder
📂	5	open file folder	file|folder|open
🗂️	5	card index dividers	card|dividers|index
📅	5	calendar	date
📆	5	tear-off calendar	calendar
🗒️	5	spiral notepad	note|pad|spiral
🗓️	5	spiral calendar	calendar|pad|spiral
📇	5	card index	card|index|rolodex
📈	5	chart increasing	chart|graph|growth|trend|upward
📉	5	chart decreasing	chart|down|graph|trend
📊	5	bar chart	bar|chart|graph
📋	5	clipboard	
📌	5	pushpin	pin
📍	5	round pushpin	pin|pushpin
📎	5	paperclip	
🖇️	5	linked paperclips	link|paperclip
📏	5	straight ruler	ruler|straight edge
📐	5	triangular ruler	ruler|set|triangle
✂️	5	scissors	cutting|tool
🗃️	5	card file box	box|card|file
🗄️	5	file cabinet	cabinet|file|filing
🗑️	5	wastebasket	
🔒	5	locked	closed
🔓	5	unlocked	lock|open|unlock
🔏	5	locked with pen	ink|lock|nib|pen|privacy
🔐	5	locked with key	closed|key|lock|secure
🔑	5	key	lock|password
🗝️	5	old key	clue|key|lock|old
🔨	5	hammer	tool
🪓	5	axe	chop|hatchet|split|wood
⛏️	5	pick	mining|tool
⚒️	5	hammer and pick	hammer|pick|tool
🛠️	5	hammer and wrench	hammer|spanner|tool|wrench
🗡️	5	dagger	knife|weapon
⚔️	5	crossed swords	crossed|swords|weapon
💣	5	bomb	comic
🪃	5	boomerang	rebound|repercussion
🏹	5	bow and arrow	archer|arrow|bow|sagittarius|zodiac
🛡️	5	shield	weapon
🪚	5	carpentry saw	carpenter|lumber|saw|tool
🔧	5	wrench	spanner|tool
🪛	5	screwdriver	screw|tool
🔩	5	nut and bolt	bolt|nut|tool
⚙️	5	gear	cog|cogwheel|tool
🗜️	5	clamp	compress|tool|vice
⚖️	5	balance scale	balance|justice|libra|scale|zodiac
🦯	5	white cane	accessibility|blind
🔗	5	link	
⛓️‍💥	5	broken chain	break|breaking|chain|cuffs|freedom
⛓️	5	chains	chain
🪝	5	hook	catch|crook|curve|ensnare|selling point
🧰	5	toolbox	chest|mechanic|tool
🧲	5	magnet	attraction|horseshoe|magnetic
🪜	5	ladder	climb|rung|step
⚗️	5	alembic	chemistry|tool
🧪	5	test tube	chemist|chemistry|experiment|lab|science
🧫	5	petri dish	bacteria|biologist|biology|culture|lab
🧬	5	dna	biologist|evolution|gene|genetics|life
🔬	5	microscope	science|tool
🔭	5	telescope	science|tool
📡	5	satellite antenna	antenna|dish|satellite
💉	5	syringe	medicine|needle|shot|sick
🩸	5	drop of blood	bleed|blood donation|injury|medicine|menstruation
💊	5	pill	doctor|medicine|sick
🩹	5	adhesive bandage	bandage
🩼	5	crutch	cane|disability|hurt|mobility aid|stick
🩺	5	stethoscope	doctor|heart|medicine
🩻	5	x-ray	bones|doctor|medical|skeleton
🚪	5	door	
🛗	5	elevator	accessibility|hoist|lift
🪞	5	mirror	reflection|reflector|speculum
🪟	5	window	frame|fresh air|opening|transparent|view
🛏️	5	bed	hotel|sleep
🛋️	5	couch and lamp	couch|hotel|lamp
🪑	5	chair	seat|sit
🚽	5	toilet	
🪠	5	plunger	force cup|plumber|suction|toilet
🚿	5	shower	water
🛁	5	bathtub	bath
🪤	5	mouse trap	bait|mousetrap|snare|trap
🪒	5	razor	sharp|shave
🧴	5	lotion bottle	lotion|moisturizer|shampoo|sunscreen
🧷	5	safety pin	diaper|punk rock
🧹	5	broom	cleaning|sweeping|witch
🧺	5	basket	farming|laundry|picnic
🧻	5	roll of paper	paper towels|toilet paper
🪣	5	bucket	cask|pail|vat
🧼	5	soap	bar|bathing|cleaning|lather|soapdish
🫧	5	bubbles	burp|clean|soap|underwater
🪥	5	toothbrush	bathroom|brush|clean|dental|hygiene|teeth
🧽	5	sponge	absorbing|cleaning|porous
🧯	5	fire extinguisher	extinguish|fire|quench
🛒	5	shopping cart	cart|shopping|trolley
🚬	5	cigarette	smoking
⚰️	5	coffin	death
🪦	5	headstone	cemetery|grave|graveyard|tombstone
⚱️	5	funeral urn	ashes|death|funeral|urn
🧿	5	nazar amulet	bead|charm|evil-eye|nazar|talisman
🪬	5	hamsa	amulet|fatima|hand|mary|miriam|protection
🗿	5	moai	face|moyai|statue
🪧	5	placard	demonstration|picket|protest|sign
🪪	5	identification card	credentials|id|license|security
🏧	6	atm sign	atm|automated|bank|teller
🚮	6	litter in bin sign	litter|litter bin
🚰	6	potable water	drinking|potable|water
♿	6	wheelchair symbol	access
🚹	6	men’s room	bathroom|lavatory|man|restroom|toilet|wc
🚺	6	women’s room	bathroom|lavatory|restroom|toilet|wc|woman
🚻	6	restroom	bathroom|lavatory|toilet|wc
🚼	6	baby symbol	baby|changing
🚾	6	water closet	bathroom|closet|lavatory|restroom|toilet|water|wc
🛂	6	passport control	control|passport
🛃	6	customs	
🛄	6	baggage claim	baggage|claim
🛅	6	left luggage	baggage|locker|luggage
⚠️	6	warning	
🚸	6	children crossing	child|crossing|pedestrian|traffic
⛔	6	no entry	entry|forbidden|no|not|prohibited|traffic
🚫	6	prohibited	entry|forbidden|no|not
🚳	6	no bicycles	bicycle|bike|forbidden|no|prohibited
🚭	6	no smoking	forbidden|no|not|prohibited|smoking
🚯	6	no littering	forbidden|litter|no|not|prohibited
🚱	6	non-potable water	non-drinking|non-potable|water
🚷	6	no pedestrians	forbidden|no|not|pedestrian|prohibited
📵	6	no mobile phones	cell|forbidden|mobile|no|phone
🔞	6	no one under eighteen	18|age restriction|eighteen|prohibited|underage
☢️	6	radioactive	sign
☣️	6	biohazard	sign
⬆️	6	up arrow	arrow|cardinal|direction|north
↗️	6	up-right arrow	arrow|direction|intercardinal|northeast
➡️	6	right arrow	arrow|cardinal|direction|east
↘️	6	down-right arrow	arrow|direction|intercardinal|southeast
⬇️	6	down arrow	arrow|cardinal|direction|down|south
↙️	6	down-left arrow	arrow|direction|intercardinal|southwest
⬅️	6	left arrow	arrow|cardinal|direction|west
↖️	6	up-left arrow	arrow|direction|intercardinal|northwest
↕️	6	up-down arrow	arrow
↔️	6	left-right arrow	arrow
↩️	6	right arrow curving left	arrow
↪️	6	left arrow curving right	arrow
⤴️	6	right arrow curving up	arrow
⤵️	6	right arrow curving down	arrow|down
🔃	6	clockwise vertical arrows	arrow|clockwise|reload
🔄	6	counterclockwise arrows button	anticlockwise|arrow|counterclockwise|withershins
🔙	6	back arrow	arrow|back
🔚	6	end arrow	arrow|end
🔛	6	on! arrow	arrow|mark|on|on!
🔜	6	soon arrow	arrow|soon
🔝	6	top arrow	arrow|top|up
🛐	6	place of worship	religion|worship
⚛️	6	atom symbol	atheist|atom
🕉️	6	om	hindu|religion
✡️	6	star of david	david|jew|jewish|religion|star
☸️	6	wheel of dharma	buddhist|dharma|religion|wheel
☯️	6	yin yang	religion|tao|taoist|yang|yin
✝️	6	latin cross	christian|cross|religion
☦️	6	orthodox cross	christian|cross|religion
☪️	6	star and crescent	islam|muslim|religion
☮️	6	peace symbol	peace
🕎	6	menorah	candelabrum|candlestick|religion
🔯	6	dotted six-pointed star	fortune|star
🪯	6	khanda	religion|sikh
♈	6	aries	ram|zodiac
♉	6	taurus	bull|ox|zodiac
♊	6	gemini	twins|zodiac
♋	6	cancer	crab|zodiac
♌	6	leo	lion|zodiac
♍	6	virgo	zodiac
♎	6	libra	balance|justice|scales|zodiac
♏	6	scorpio	scorpion|scorpius|zodiac
♐	6	sagittarius	archer|zodiac
♑	6	capricorn	goat|zodiac
♒	6	aquarius	bearer|water|zodiac
♓	6	pisces	fish|zodiac
⛎	6	ophiuchus	bearer|serpent|snake|zodiac
🔀	6	shuffle tracks button	arrow|crossed
🔁	6	repeat button	arrow|clockwise|repeat
🔂	6	repeat single button	arrow|clockwise|once
▶️	6	play button	arrow|play|right|triangle
⏩	6	fast-forward button	arrow|double|fast|forward
⏭️	6	next track button	arrow|next scene|next track|triangle
⏯️	6	play or pause button	arrow|pause|play|right|triangle
◀️	6	reverse button	arrow|left|reverse|triangle
⏪	6	fast reverse button	arrow|double|rewind
⏮️	6	last track button	arrow|previous scene|previous track|triangle
🔼	6	upwards button	arrow|button
⏫	6	fast up button	arrow|double
🔽	6	downwards button	arrow|button|down
⏬	6	fast down button	arrow|double|down
⏸️	6	pause button	bar|double|pause|vertical
⏹️	6	stop button	square|stop
⏺️	6	record button	circle|record
⏏️	6	eject button	eject
🎦	6	cinema	camera|film|movie
🔅	6	dim button	brightness|dim|low
🔆	6	bright button	bright|brightness
📶	6	antenna bars	antenna|bar|cell|mobile|phone
🛜	6	wireless	computer|internet|network|wi-fi|wifi
📳	6	vibration mode	cell|mobile|mode|phone|telephone|vibration
📴	6	mobile phone off	cell|mobile|off|phone|telephone
♀️	6	female sign	woman
♂️	6	male sign	man
⚧️	6	transgender symbol	transgender
✖️	6	multiply	×|cancel|multiplication|sign|x
➕	6	plus	+|math|sign
➖	6	minus	-|−|math|sign
➗	6	divide	÷|division|math|sign
🟰	6	heavy equals sign	equality|math
♾️	6	infinity	forever|unbounded|universal
‼️	6	double exclamation mark	!|!!|bangbang|exclamation|mark
⁉️	6	exclamation question mark	!|!?|?|exclamation|interrobang|mark|punctuation|question
❓	6	red question mark	?|mark|punctuation|question
❔	6	white question mark	?|mark|outlined|punctuation|question
❕	6	white exclamation mark	!|exclamation|mark|outlined|punctuation
❗	6	red exclamation mark	!|exclamation|mark|punctuation
〰️	6	wavy dash	dash|punctuation|wavy
💱	6	currency exchange	bank|currency|exchange|money
💲	6	heavy dollar sign	currency|dollar|money
⚕️	6	medical symbol	aesculapius|medicine|staff
♻️	6	recycling symbol	recycle
⚜️	6	fleur-de-lis	
🔱	6	trident emblem	anchor|emblem|ship|tool|trident
📛	6	name badge	badge|name
🔰	6	japanese symbol for beginner	beginner|chevron|japanese|leaf
⭕	6	hollow red circle	circle|large|o|red
✅	6	check mark button	✓|button|check|mark
☑️	6	check box with check	✓|box|check
✔️	6	check mark	✓|check|mark
❌	6	cross mark	×|cancel|cross|mark|multiplication|multiply|x
❎	6	cross mark button	×|mark|square|x
➰	6	curly loop	curl|loop
➿	6	double curly loop	curl|double|loop
〽️	6	part alternation mark	mark|part
✳️	6	eight-spoked asterisk	*|asterisk
✴️	6	eight-pointed star	*|star
❇️	6	sparkle	*
©️	6	copyright	c
®️	6	registered	r
™️	6	trade mark	mark|tm|trademark
#️⃣	6	keycap: #	keycap
*️⃣	6	keycap: *	keycap
0️⃣	6	keycap: 0	keycap
1️⃣	6	keycap: 1	keycap
2️⃣	6	keycap: 2	keycap
3️⃣	6	keycap: 3	keycap
4️⃣	6	keycap: 4	keycap
5️⃣	6	keycap: 5	keycap
6️⃣	6	keycap: 6	keycap
7️⃣	6	keycap: 7	keycap
8️⃣	6	keycap: 8	keycap
9️⃣	6	keycap: 9	keycap
🔟	6	keycap: 10	keycap
🔠	6	input latin uppercase	abcd|input|latin|letters|uppercase
🔡	6	input latin lowercase	abcd|input|latin|letters|lowercase
🔢	6	input numbers	1234|input|numbers
🔣	6	input symbols	〒♪&%|input
🔤	6	input latin letters	abc|alphabet|input|latin|letters
🅰️	6	a button (blood type)	a|blood type
🆎	6	ab button (blood type)	ab|blood type
🅱️	6	b button (blood type)	b|blood type
🆑	6	cl button	cl
🆒	6	cool button	cool
🆓	6	free button	free
ℹ️	6	information	i
🆔	6	id button	id|identity
Ⓜ️	6	circled m	circle|m
🆕	6	new button	new
🆖	6	ng button	ng
🅾️	6	o button (blood type)	blood type|o
🆗	6	ok button	ok
🅿️	6	p button	p|parking
🆘	6	sos button	help|sos
🆙	6	up! button	mark|up|up!
🆚	6	vs button	versus|vs
🈁	6	japanese “here” button	“here”|japanese|katakana|ココ
🈂️	6	japanese “service charge” button	“service charge”|japanese|katakana|サ
🈷️	6	japanese “monthly amount” button	“monthly amount”|ideograph|japanese|月
🈶	6	japanese “not free of charge” button	“not free of charge”|ideograph|japanese|有
🈯	6	japanese “reserved” button	“reserved”|ideograph|japanese|指
🉐	6	japanese “bargain” button	“bargain”|ideograph|japanese|得
🈹	6	japanese “discount” button	“discount”|ideograph|japanese|割
🈚	6	japanese “free of charge” button	“free of charge”|ideograph|japanese|無
🈲	6	japanese “prohibited” button	“prohibited”|ideograph|japanese|禁
🉑	6	japanese “acceptable” button	“acceptable”|ideograph|japanese|可
🈸	6	japanese “application” button	“application”|ideograph|japanese|申
🈴	6	japanese “passing grade” button	“passing grade”|ideograph|japanese|合
🈳	6	japanese “vacancy” button	“vacancy”|ideograph|japanese|空
㊗️	6	japanese “congratulations” button	“congratulations”|ideograph|japanese|祝
㊙️	6	japanese “secret” button	“secret”|ideograph|japanese|秘
🈺	6	japanese “open for business” button	“open for business”|ideograph|japanese|営
🈵	6	japanese “no vacancy” button	“no vacancy”|ideograph|japanese|満
🔴	6	red circle	circle|geometric|red
🟠	6	orange circle	circle|orange
🟡	6	yellow circle	circle|yellow
🟢	6	green circle	circle|green
🔵	6	blue circle	blue|circle|geometric
🟣	6	purple circle	circle|purple
🟤	6	brown circle	brown|circle
⚫	6	black circle	circle|geometric
⚪	6	white circle	circle|geometric
🟥	6	red square	red|square
🟧	6	orange square	orange|square
🟨	6	yellow square	square|yellow
🟩	6	green square	green|square
🟦	6	blue square	blue|square
🟪	6	purple square	purple|square
🟫	6	brown square	brown|square
⬛	6	black large square	geometric|square
⬜	6	white large square	geometric|square
◼️	6	black medium square	geometric|square
◻️	6	white medium square	geometric|square
◾	6	black medium-small square	geometric|square
◽	6	white medium-small square	geometric|square
▪️	6	black small square	geometric|square
▫️	6	white small square	geometric|square
🔶	6	large orange diamond	diamond|geometric|orange
🔷	6	large blue diamond	blue|diamond|geometric
🔸	6	small orange diamond	diamond|geometric|orange
🔹	6	small blue diamond	blue|diamond|geometric
🔺	6	red triangle pointed up	geometric|red
🔻	6	red triangle pointed down	down|geometric|red
💠	6	diamond with a dot	comic|diamond|geometric|inside
🔘	6	radio button	button|geometric|radio
🔳	6	white square button	button|geometric|outlined|square
🔲	6	black square button	button|geometric|square
🏁	7	chequered flag	checkered|chequered|racing
🚩	7	triangular flag	post
🎌	7	crossed flags	celebration|cross|crossed|japanese
🏴	7	black flag	waving
🏳️	7	white flag	waving
🏳️‍🌈	7	rainbow flag	pride|rainbow
🏳️‍⚧️	7	transgender flag	flag|light blue|pink|transgender|white
🏴‍☠️	7	pirate flag	jolly roger|pirate|plunder|treasure
🇦🇨	7	flag: ascension island	flag
🇦🇩	7	flag: andorra	flag
🇦🇪	7	flag: united arab emirates	flag
🇦🇫	7	flag: afghanistan	flag
🇦🇬	7	flag: antigua & barbuda	flag
🇦🇮	7	flag: anguilla	flag
🇦🇱	7	flag: albania	flag
🇦🇲	7	flag: armenia	flag
🇦🇴	7	flag: angola	flag
🇦🇶	7	flag: antarctica	flag
🇦🇷	7	flag: argentina	flag
🇦🇸	7	flag: american samoa	flag
🇦🇹	7	flag: austria	flag
🇦🇺	7	flag: australia	flag
🇦🇼	7	flag: aruba	flag
🇦🇽	7	flag: åland islands	flag
🇦🇿	7	flag: azerbaijan	flag
🇧🇦	7	flag: bosnia & herzegovina	flag
🇧🇧	7	flag: barbados	flag
🇧🇩	7	flag: bangladesh	flag
🇧🇪	7	flag: belgium	flag
🇧🇫	7	flag: burkina faso	flag
🇧🇬	7	flag: bulgaria	flag
🇧🇭	7	flag: bahrain	flag
🇧🇮	7	flag: burundi	flag
🇧🇯	7	flag: benin	flag
🇧🇱	7	flag: st. barthélemy	flag
🇧🇲	7	flag: bermuda	flag
🇧🇳	7	flag: brunei	flag
🇧🇴	7	flag: bolivia	flag
🇧🇶	7	flag: caribbean netherlands	flag
🇧🇷	7	flag: brazil	flag
🇧🇸	7	flag: bahamas	flag
🇧🇹	7	flag: bhutan	flag
🇧🇻	7	flag: bouvet island	flag
🇧🇼	7	flag: botswana	flag
🇧🇾	7	flag: belarus	flag
🇧🇿	7	flag: belize	flag
🇨🇦	7	flag: canada	flag
🇨🇨	7	flag: cocos (keeling) islands	flag
🇨🇩	7	flag: congo - kinshasa	flag
🇨🇫	7	flag: central african republic	flag
🇨🇬	7	flag: congo - brazzaville	flag
🇨🇭	7	flag: switzerland	flag
🇨🇮	7	flag: côte d’ivoire	flag
🇨🇰	7	flag: cook islands	flag
🇨🇱	7	flag: chile	flag
🇨🇲	7	flag: cameroon	flag
🇨🇳	7	flag: china	flag
🇨🇴	7	flag: colombia	flag
🇨🇵	7	flag: clipperton island	flag
🇨🇷	7	flag: costa rica	flag
🇨🇺	7	flag: cuba	flag
🇨🇻	7	flag: cape verde	flag
🇨🇼	7	flag: curaçao	flag
🇨🇽	7	flag: christmas island	flag
🇨🇾	7	flag: cyprus	flag
🇨🇿	7	flag: czechia	flag
🇩🇪	7	flag: germany	flag
🇩🇬	7	flag: diego garcia	flag
🇩🇯	7	flag: djibouti	flag
🇩🇰	7	flag: denmark	flag
🇩🇲	7	flag: dominica	flag
🇩🇴	7	flag: dominican republic	flag
🇩🇿	7	flag: algeria	flag
🇪🇦	7	flag: ceuta & melilla	flag
🇪🇨	7	flag: ecuador	flag
🇪🇪	7	flag: estonia	flag
🇪🇬	7	flag: egypt	flag
🇪🇭	7	flag: western sahara	flag
🇪🇷	7	flag: eritrea	flag
🇪🇸	7	flag: spain	flag
🇪🇹	7	flag: ethiopia	flag
🇪🇺	7	flag: european union	flag
🇫🇮	7	flag: finland	flag
🇫🇯	7	flag: fiji	flag
🇫🇰	7	flag: falkland islands	flag
🇫🇲	7	flag: micronesia	flag
🇫🇴	7	flag: faroe islands	flag
🇫🇷	7	flag: france	flag
🇬🇦	7	flag: gabon	flag
🇬🇧	7	flag: united kingdom	flag
🇬🇩	7	flag: grenada	flag
🇬🇪	7	flag: georgia	flag
🇬🇫	7	flag: french guiana	flag
🇬🇬	7	flag: guernsey	flag
🇬🇭	7	flag: ghana	flag
🇬🇮	7	flag: gibraltar	flag
🇬🇱	7	flag: greenland	flag
🇬🇲	7	flag: gambia	flag
🇬🇳	7	flag: guinea	flag
🇬🇵	7	flag: guadeloupe	flag
🇬🇶	7	flag: equatorial guinea	flag
🇬🇷	7	flag: greece	flag
🇬🇸	7	flag: south georgia & south sandwich islands	flag
🇬🇹	7	flag: guatemala	flag
🇬🇺	7	flag: guam	flag
🇬🇼	7	flag: guinea-bissau	flag
🇬🇾	7	flag: guyana	flag
🇭🇰	7	flag: hong kong sar china	flag
🇭🇲	7	flag: heard & mcdonald islands	flag
🇭🇳	7	flag: honduras	flag
🇭🇷	7	flag: croatia	flag
🇭🇹	7	flag: haiti	flag
🇭🇺	7	flag: hungary	flag
🇮🇨	7	flag: canary islands	flag
🇮🇩	7	flag: indonesia	flag
🇮🇪	7	flag: ireland	flag
🇮🇱	7	flag: israel	flag
🇮🇲	7	flag: isle of man	flag
🇮🇳	7	flag: india	flag
🇮🇴	7	flag: british indian ocean territory	flag
🇮🇶	7	flag: iraq	flag
🇮🇷	7	flag: iran	flag
🇮🇸	7	flag: iceland	flag
🇮🇹	7	flag: italy	flag
🇯🇪	7	flag: jersey	flag
🇯🇲	7	flag: jamaica	flag
🇯🇴	7	flag: jordan	flag
🇯🇵	7	flag: japan	flag
🇰🇪	7	flag: kenya	flag
🇰🇬	7	flag: kyrgyzstan	flag
🇰🇭	7	flag: cambodia	flag
🇰🇮	7	flag: kiribati	flag
🇰🇲	7	flag: comoros	flag
🇰🇳	7	flag: st. kitts & nevis	flag
🇰🇵	7	flag: north korea	flag
🇰🇷	7	flag: south korea	flag
🇰🇼	7	flag: kuwait	flag
🇰🇾	7	flag: cayman islands	flag
🇰🇿	7	flag: kazakhstan	flag
🇱🇦	7	flag: laos	flag
🇱🇧	7	flag: lebanon	flag
🇱🇨	7	flag: st. lucia	flag
🇱🇮	7	flag: liechtenstein	flag
🇱🇰	7	flag: sri lanka	flag
🇱🇷	7	flag: liberia	flag
🇱🇸	7	flag: lesotho	flag
🇱🇹	7	flag: lithuania	flag
🇱🇺	7	flag: luxembourg	flag
🇱🇻	7	flag: latvia	flag
🇱🇾	7	flag: libya	flag
🇲🇦	7	flag: morocco	flag
🇲🇨	7	flag: monaco	flag
🇲🇩	7	flag: moldova	flag
🇲🇪	7	flag: montenegro	flag
🇲🇫	7	flag: st. martin	flag
🇲🇬	7	flag: madagascar	flag
🇲🇭	7	flag: marshall islands	flag
🇲🇰	7	flag: north macedonia	flag
🇲🇱	7	flag: mali	flag
🇲🇲	7	flag: myanmar (burma)	flag
🇲🇳	7	flag: mongolia	flag
🇲🇴	7	flag: macao sar china	flag
🇲🇵	7	flag: northern mariana islands	flag
🇲🇶	7	flag: martinique	flag
🇲🇷	7	flag: mauritania	flag
🇲🇸	7	flag: montserrat	flag
🇲🇹	7	flag: malta	flag
🇲🇺	7	flag: mauritius	flag
🇲🇻	7	flag: maldives	flag
🇲🇼	7	flag: malawi	flag
🇲🇽	7	flag: mexico	flag
🇲🇾	7	flag: malaysia	flag
🇲🇿	7	flag: mozambique	flag
🇳🇦	7	flag: namibia	flag
🇳🇨	7	flag: new caledonia	flag
🇳🇪	7	flag: niger	flag
🇳🇫	7	flag: norfolk island	flag
🇳🇬	7	flag: nigeria	flag
🇳🇮	7	flag: nicaragua	flag
🇳🇱	7	flag: netherlands	flag
🇳🇴	7	flag: norway	flag
🇳🇵	7	flag: nepal	flag
🇳🇷	7	flag: nauru	flag
🇳🇺	7	flag: niue	flag
🇳🇿	7	flag: new zealand	flag
🇴🇲	7	flag: oman	flag
🇵🇦	7	flag: panama	flag
🇵🇪	7	flag: peru	flag
🇵🇫	7	flag: french polynesia	flag
🇵🇬	7	flag: papua new guinea	flag
🇵🇭	7	flag: philippines	flag
🇵🇰	7	flag: pakistan	flag
🇵🇱	7	flag: poland	flag
🇵🇲	7	flag: st. pierre & miquelon	flag
🇵🇳	7	flag: pitcairn islands	flag
🇵🇷	7	flag: puerto rico	flag
🇵🇸	7	flag: palestinian territories	flag
🇵🇹	7	flag: portugal	flag
🇵🇼	7	flag: palau	flag
🇵🇾	7	flag: paraguay	flag
🇶🇦	7	flag: qatar	flag
🇷🇪	7	flag: réunion	flag
🇷🇴	7	flag: romania	flag
🇷🇸	7	flag: serbia	flag
🇷🇺	7	flag: russia	flag
🇷🇼	7	flag: rwanda	flag
🇸🇦	7	flag: saudi arabia	flag
🇸🇧	7	flag: solomon islands	flag
🇸🇨	7	flag: seychelles	flag
🇸🇩	7	flag: sudan	flag
🇸🇪	7	flag: sweden	flag
🇸🇬	7	flag: singapore	flag
🇸🇭	7	flag: st. helena	flag
🇸🇮	7	flag: slovenia	flag
🇸🇯	7	flag: svalbard & jan mayen	flag
🇸🇰	7	flag: slovakia	flag
🇸🇱	7	flag: sierra leone	flag
🇸🇲	7	flag: san marino	flag
🇸🇳	7	flag: senegal	flag
🇸🇴	7	flag: somalia	flag
🇸🇷	7	flag: suriname	flag
🇸🇸	7	flag: south sudan	flag
🇸🇹	7	flag: são tomé & príncipe	flag
🇸🇻	7	flag: el salvador	flag
🇸🇽	7	flag: sint maarten	flag
🇸🇾	7	flag: syria	flag
🇸🇿	7	flag: eswatini	flag
🇹🇦	7	flag: tristan da cunha	flag
🇹🇨	7	flag: turks & caicos islands	flag
🇹🇩	7	flag: chad	flag
🇹🇫	7	flag: french southern territories	flag
🇹🇬	7	flag: togo	flag
🇹🇭	7	flag: thailand	flag
🇹🇯	7	flag: tajikistan	flag
🇹🇰	7	flag: tokelau	flag
🇹🇱	7	flag: timor-leste	flag
🇹🇲	7	flag: turkmenistan	flag
🇹🇳	7	flag: tunisia	flag
🇹🇴	7	flag: tonga	flag
🇹🇷	7	flag: türkiye	flag
🇹🇹	7	flag: trinidad & tobago	flag
🇹🇻	7	flag: tuvalu	flag
🇹🇼	7	flag: taiwan	flag
🇹🇿	7	flag: tanzania	flag
🇺🇦	7	flag: ukraine	flag
🇺🇬	7	flag: uganda	flag
🇺🇲	7	flag: u.s. outlying islands	flag
🇺🇳	7	flag: united nations	flag
🇺🇸	7	flag: united states	flag
🇺🇾	7	flag: uruguay	flag
🇺🇿	7	flag: uzbekistan	flag
🇻🇦	7	flag: vatican city	flag
🇻🇨	7	flag: st. vincent & grenadines	flag
🇻🇪	7	flag: venezuela	flag
🇻🇬	7	flag: british virgin islands	flag
🇻🇮	7	flag: u.s. virgin islands	flag
🇻🇳	7	flag: vietnam	flag
🇻🇺	7	flag: vanuatu	flag
🇼🇫	7	flag: wallis & futuna	flag
🇼🇸	7	flag: samoa	flag
🇽🇰	7	flag: kosovo	flag
🇾🇪	7	flag: yemen	flag
🇾🇹	7	flag: mayotte	flag
🇿🇦	7	flag: south africa	flag
🇿🇲	7	flag: zambia	flag
🇿🇼	7	flag: zimbabwe	flag
🏴󠁧󠁢󠁥󠁮󠁧󠁿	7	flag: england	flag
🏴󠁧󠁢󠁳󠁣󠁴󠁿	7	flag: scotland	flag
🏴󠁧󠁢󠁷󠁬󠁳󠁿	7	flag: wales	flag""",
)
